### ISSUE TITLE
[How to] Get and restore right format

### ISSUE THREAD

**Issue by Spadino75** [KillerCodeMonkey/ngx-quill#1012]
Hello,
I got an angular 4.0 project with ngx-quill 1.6.0 and I am using chrome browser. I have this issue, I open the editor, create a nice text with some style and get back in the component the output like:
`"<h1>First H1 row</h1><h2>Second H2 row</h2><p><strong>Bold row</strong></p><p><strong><em>Bold italic row</em></strong></p>".`
I store the value in the database then I close the form, when I go back and put the string to the quill editor with setText(..) method I can't see anymore the nice format but a simple:
`"<p>First`` H1 rowSecond H2 row<strong>Bold row<em>Bold italic `row</em></strong></p>"`
but the source string was exactly what I got before from the quill editor :-(

This is my view definition
`<quill-editor` formControlName="Description" class="no-background-color" `ng></quill-editor>`

and this the code where I put the value:
this.positionForm.controls.Description.setValue(currentPosition.Position_Description);

The quill editor is related to a FormControl:
Description: new FormControl('', Validators.required),

What is wrong? I don't have so much experience on Angular and can't upgrade to new Angular version :-(

Can you help me?
Many thanks in advance!

**Comment by KillerCodeMonkey** [comment]
1. i am not support such old ngx-quill or angular versions -> check the readme
2. ` setText(..)` like the name of the method says it handles your string as text and not html string...

you can just use a quill-editor component to put the content in there instead of the quilljs api.
or you need to use the quilljs api in the right way:

https://github.com/KillerCodeMonkey/ngx-quill/blob/master/projects/ngx-quill/src/lib/quill-editor.component.ts#L166
https://github.com/KillerCodeMonkey/ngx-quill/blob/master/projects/ngx-quill/src/lib/quill-editor.component.ts#L510

so 1. convert your html string object representation 2. use setContents function to set the content.
