### ISSUE TITLE
Add custom button and custom styling

### ISSUE THREAD

**Issue by larearruda** [KillerCodeMonkey/ngx-quill#1013]
I'm developing a **mailing list** feature in my Ionic v3 app I would like to some guidance on how customize it in order to create a button that would allow users to insert text aliases within the message, so I could read it in the mailing feature and replace it for the database information. 

For that custom button, my first thought was to create something similar to the `ql-align` button: A `<select></select>` element followed by `<option></option>` elements providing the list of available aliases parameters to insert in the message. Something like

    <select class="custom-parameters" [title]="'Custom Parameters'">
        <option selected></option>
        <option value="user_name"></option>
        <option value="request_number"></option>
    </select>

Each option would insert some sort of identification within that tag. And by that, I mean:

`<a href="#" class="user_name"></p>`

Or

`<a href="#" class="request_number"></p>`

I used the `<a></a>` tag as example, but it could be any other property, as long it can help me find the information within the message and replace it.

I have found this GitHub issue [How to add custom button? Full working example][1] but it was not clear enough to me on how can I apply the `class="username"` and `class="request_number"` styling classes. 

Any other ideas on solving this would be very much appreciated.

Platform information:

    "ionic-angular": "3.9.2",
    "ngx-quill": "^1.6.0",
    "quill": "^1.3.7",
    "rxjs": "5.5.2",

  [1]: https://github.com/quilljs/quill/issues/2611

**Comment by KillerCodeMonkey** [comment]
heyho

in the example you linked, you see that you need to register custom formats - class names, attributes, tags in quill, because quill only allows to add known things to the editor.

```TS
var Parchment = Quill.import("parchment");

let CustomClass = new Parchment.Attributor.Class('custom', 'ql-custom', {
  scope: Parchment.Scope.INLINE
});

Quill.register(CustomClass, true);
```

So this code block say quill: here i have a custom class that i allowed to use.

then you can style your `ql-custom` class. thats it.
A more maintainable way would be to create a whole new Blot:

https://github.com/quilljs/parchment#example

But if i can suggest you something:
Check out quill-mention:

https://github.com/afry/quill-mention
Example: https://afry.github.io/quill-mention/

you see that you get some auto-suggestion and styling for free + you could create your toolbar select with all your "mentions" - if you select one, just insert the mention-span as you can see it in the example.

+ you can configure that module what "indicator chars" you wanna have, if `@` is not working for your use case, and you can configure that this mention indicator char is wrapped in another span if a special classname.
So if you wanna replace your placeholder late it is easy money.

Sadly since this is a general quill question it is not an issue with this repo. i will close it.

Please use stack overflow or something similar next time ;-)
