### ISSUE TITLE
Cannot override property as an accessor

### ISSUE THREAD

**Issue by jguitarz** [KillerCodeMonkey/ngx-quill#1047]
See: [stack blitz demo](https://stackblitz.com/edit/angular-ivy-xuyu28?file=src/app/mat-quill/mat-quill-base.ts)

I am trying to implement the material version like you have in your ngx-quill-example repository. However, I keep running into this error in `mat-quill-base.ts`:

> 'disabled' is defined as a property in class 'CanUpdateErrorState & CanDisable & MatQuillBase', but is overridden here in '_MatQuillBase' as an accessor.

I get two more of the same error for `placeholder` and `required`.

How can I resolve these errors?

**Comment by KillerCodeMonkey** [comment]
like the error says, you are defining those as inputs with getter and setter, and this is not expected.
in general i do not give support for material ui things. since this is only an example in the demp repo a contributor added.

i do not like the complexity of material ui and would just style the editor in the material ui way ;-)
