### ISSUE TITLE
custom toolbar button dynamic styling

### ISSUE THREAD

**Issue by Eraldo** [KillerCodeMonkey/ngx-quill#1064]
If I have a custom button (within a custom toolbar `quill-editor-toolbar` selector) like this:
```
    <ion-button class="ql-bold">
      <ion-icon name="bold" slot="icon-only"></ion-icon>
    </ion-button>
```
How can would I best make that button reflect the current cursor position (change the button style if the current cursor position currently has formatting bold enabled)?

Best practise suggestions? :)

**Comment by KillerCodeMonkey** [comment]
Just use the selectionChange and content Change Outputs.

And exexute https://quilljs.com/docs/api/#getformat

If no custom range is passed, you will get the Formats of the current
selection.

Then it is up to you to mark your custom toolbar buttons as active :)

Eraldo Energy <notifications@github.com> schrieb am So., 25. Okt. 2020,
00:37:

**Comment by Eraldo** [comment]
I see. Thanks, I'll try that.

Is there also a way of reusing existing logic like toggleBold, etc. Or do I have to reimplement all of that from scratch if I have my own custom html toolbar?

(I have a bit of a challenge understanding everything that happens in the toolbar module that is part of quill. Also some of the methods used in there are not part of the api and I did not manage to get them to work when using from outside the quill environment.)

Also, using 3rd party extensions might also get more complicated since the way I understand it, they somehow hook into the toolbar. But that is just my impression right now. I will try out more to learn and see what particular challenges I run into.

Thanks for your feedback. :)
And if you have any ideas of how to reuse existing logic, please tell me.

**Comment by KillerCodeMonkey** [comment]
for the reuse purpose you could try to build a custom toolbar component and place it inside of 

```
<div quill-editor-toolbar><custom-toolbar></custom-toolbar></div>
```

You could even try to pass the editor in there as an input and only render it, when the editor is defined:
```
<div quill-editor-toolbar><custom-toolbar *ngIf="!!editor" [editor]="editor"></custom-toolbar></div>
```

So you are able to directly use the quilljs editor api :)

PS: This is just thinking loud.. i do not know if this will really work in the end. but why not?

**Comment by Eraldo** [comment]
As I understand it, if I create my own toolbar that way, I will not be able to use existing extensions like `quill-html-edit-button` because they expect the non custom toolbar to be there. E.g: https://github.com/benwinding/quill-html-edit-button/blob/master/src/quill.htmlEditButton.js#L32

And I would also have to reimplement the logic that comes with toolbar.js since that logic seems to be tightly coupled and not really reusable without complete reimplementation. :|

**Comment by KillerCodeMonkey** [comment]
if i understand that custom button correctly, it just checks if a toolbar is initialised.
and in case of a custom toolbar - it is:

https://github.com/KillerCodeMonkey/ngx-quill/blob/master/projects/ngx-quill/src/lib/quill-editor.component.ts#L194

the only deal breaker is, that this module just appends a button to the toolbar, so it could be that you are limited how and where you can place this button.

Not to be disrespectful, but in general this html edito button thing does not look like golden piece of code.

In general quilljs is a good editor, because you are not allowed to manipulate the html as a use :D.

In your case you could even add a custom button to your toolbar and pass your current html content in a modal/dialog with a text area. Allow to manipulate the html and pass it back to your content/ngModel/formControl. Then the ordinary html formatting and validation kicks in of ngx-quill and quilljs. 

Thats it.

**Comment by Eraldo** [comment]
I actually ended up writing a wrapper for your wrapper to be able to add services to the constructor.
When it comes to the whole topic of custom toolbar buttons I am still struggling.
However I will close this issue for now since I see it more of a discussion topic than a specific issue for feature request.
Thanks @KillerCodeMonkey for your insights. And yes I can see the "not golden piece of code" aspect. *giggle*
