### ISSUE TITLE
There is no FormControl instance attached to form control element

### ISSUE THREAD

**Issue by feco93** [KillerCodeMonkey/ngx-quill#108]
I have a formgroup with some formcontrols. On the view there is a selectbox, when the selection changing I call this angular method:
this.tabForm.setControl('selectedHtmlControl', control); -> where control is an AbstractControl instance.

After calling the above method I receive this error message:

` 
Error: There is no FormControl instance attached to form control element with name: 'selectedHtmlControl'
forms.js:2427
    at _throwError (myProject\node_modules\@angular\forms\esm5\forms.js:2427:1)
    at _noControlError (myProject\node_modules\@angular\forms\esm5\forms.js:2409:1)
    at QuillComponent.eval [as onModelTouched] (myProject\node_modules\@angular\forms\esm5\forms.js:2324:58)
    at Emitter.eval (myProject\node_modules\ngx-quill\src\quill-editor.component.js:96:1)
    at Emitter.emit (myProject\node_modules\quill\dist\quill.js:8505:1)
    at Emitter.emit (myProject\node_modules\quill\dist\quill.js:1893:1)
    at Selection.update (myProject\node_modules\quill\dist\quill.js:3199:1)
    at eval (myProject\node_modules\quill\dist\quill.js:2871:1)
    at eval (myProject\node_modules\quill\dist\quill.js:1907:1)
    at Array.forEach (<anonymous>)
`

**Comment by KillerCodeMonkey** [comment]
Why are you using setControl to overwrite a Control on changing the
selection?

Do you have different quill instances?

More Details or a Demo as a plunkr or codepen would be Nice.

How do you add the formControl in the Template?



Am 05.02.2018 21:02 schrieb "feco93" <notifications@github.com>:

I have a formgroup with some formcontrols. On the view there is a
selectbox, when the selection changing I call this angular method:
this.tabForm.setControl('selectedHtmlControl', control); -> where control
is an AbstractControl instance.

After calling the above method I receive this error message:

Error: There is no FormControl instance attached to form control element
with name: 'selectedHtmlControl' forms.js:2427 at _throwError
(myProject\node_modules\@angular\forms\esm5\forms.js:2427:1) at
_noControlError (myProject\node_modules\@angular\forms\esm5\forms.js:2409:1)
at QuillComponent.eval [as onModelTouched] (myProject\node_modules\@
angular\forms\esm5\forms.js:2324:58) at Emitter.eval
(myProject\node_modules\ngx-quill\src\quill-editor.component.js:96:1) at
Emitter.emit (myProject\node_modules\quill\dist\quill.js:8505:1) at
Emitter.emit (myProject\node_modules\quill\dist\quill.js:1893:1) at
Selection.update (myProject\node_modules\quill\dist\quill.js:3199:1) at
eval (myProject\node_modules\quill\dist\quill.js:2871:1) at eval
(myProject\node_modules\quill\dist\quill.js:1907:1) at Array.forEach
(<anonymous>)

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/KillerCodeMonkey/ngx-quill/issues/108>, or mute the
thread

**Comment by feco93** [comment]
Plunker link: https://plnkr.co/edit/Vs1nVcqAqumeqUuYKjHo
Demonstrates the problem. When you change quill-editor to for example simple text input, it works well.

**Comment by feco93** [comment]
I use this approach, because I have more than one text input, but in one time the user only set one text input (with quill editor) and with the select-box can change between text inputs.

**Comment by KillerCodeMonkey** [comment]
Thanks, Maybe you can Help me to find the root of the Problem. I followed
the angular Guides when i created this component to work with ngModel and
reactive Forms.

I do not know what i missed. So any Info would be helpful. I Made a quick
google search and found many issues, but no fix or what could cause this
Problem in a custom Input.

Maybe you need to reinstantiate the quill-editor. Like removing it with
ngIf from the dom, then setting the Control and after that readd the
editor.

Maybe this is a workaround.


Am 05.02.2018 22:00 schrieb "feco93" <notifications@github.com>:

**Comment by KillerCodeMonkey** [comment]
@feco93 i added an example to the demo-repo.

seems like custom inputs/formcontrols with `formControlName` are only one-time-binded.
so you need to use this:

```
<quill-editor [formControl]="form.controls['editor']"></quill-editor>
```

If you use setControl --> editor stores a new reference, but because it is only one-time-binded it does not get the new reference - it only loses the initial one.
If you use the `[formControl]` it explicit creates a one-way-binding where it updates the reference on changes.

Hope this helps and fullfils your needs.

Please, close this issue if this is okay :)

**Comment by feco93** [comment]
I have tried this with no success. If you use this approach, when you set form.controls['editor'] to a new reference, the previous form.controls['editor'] 's value overwritten by the new formcontrol value.

I don't know whether it is an angular bug or not.

The reinstantiating workaround works, but not too elegant and reloads the whole quill editor component.

**Comment by KillerCodeMonkey** [comment]
so but i would expect, if i set a new control on an existing formControlName, that the value of the new controls is set?

This is the only way it makes sense?

In your case i would not create a control for each language --> simply store an alias as the value of the select-options.

if the selection changes --> create a new Control with the value you want ;).
or simply reuse the control and if you want to save your changes, combine the selected value in the dropdown and the value in the model.

So no need to create useless controls.

**Comment by feco93** [comment]
But when changing the drop-down value the form should remember the previus HTML content, so I thought I should use FormControls and I can easily manage this feature. When drop-down selection changes I just bind the selected form control to quill editor. If I not use form controls I have to manage cache and validations and so on.

If you have a better solution, share with me. :)

**Comment by KillerCodeMonkey** [comment]
okay but maybe we can achieve your goal with another approach:

You have correctly a FormArray with all your language dependent controls.
Do not explicit store the current selected one.

simply store the index of the current active language --> and then:

```
<quill-editor [formControl]="form.controls['localizations'][activeLanguageIndex]"></quill-editor>
```

So you are not hacky overwrite existing ones, and you do not need another Control :)

PS: I do not tested the code... so maybe you should use form.get('localizations') and so on. it only should get you the idea how to solve your problem smart :)

**Comment by feco93** [comment]
I  just store a reference to the selected language:
`this.selectedHtmlControl = this.tabForm.get('localizations.' + index);`

And in the view:
`<quill-editor [formControl]="selectedHtmlControl"></quill-editor>`

It doesn't work well. The new form control 's value overwrite the previous form control value. If I set selectedHtmlControl to undefined and use an ngIf in the view, it works:

```
<ng-container *ngIf="selectedHtmlControl">
                        <quill-editor [formControl]="selectedHtmlControl"></quill-editorl>
                    </ng-container>
```

**Comment by KillerCodeMonkey** [comment]
How many languages do you have?
another approach --> render all editors but hide them with `[hidden]="!activeLanguage"`

so all editors are prerendered and you can toggle the active one.

**Comment by feco93** [comment]
Max 100.

**Comment by KillerCodeMonkey** [comment]
Waaaaaaat 100 languages Oo what service do you developing…

BTW: just at an partial loading spinner if the editor is instantiated, so every time a user changes the language the loading-container shows up —> and you can hide it when „onEditorCreated“ is called.

**Comment by feco93** [comment]
I will use this approach. When I have got free time, i will deal with this (bug?).

Thanks for suggestions and quick reply. :)

If I solve this problem i will create a PR.

Ps: Sorry for my english.

**Comment by KillerCodeMonkey** [comment]
okay. no problem and do not excuse for your "english". if i understand the context of your message everything is fine. ;)

I do not know, maybe switching the formControl dynamically how do you want to do it is not possbile with "this" kind of custom formControl ngx-quill is.

I will close this issue, but i will check that again.
