### ISSUE TITLE
Update to Angular 11

### ISSUE THREAD

**Issue by arobert93** [KillerCodeMonkey/ngx-quill#1085]
Hi there,

Do you plan to upgrade to Angular 11 to avoid --force install?

**Comment by KillerCodeMonkey** [comment]
Sure. AS fast AS i have time for IT.

If you Like you could create a pr allowing angular 11 + all of the
dependencies


Am 18.11.2020 in 12:56, Alexandru Comanescu <notifications@github.com>
schrieb:

Hi there,

Do you plan to upgrade to Angular 11 to avoid --force install?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/KillerCodeMonkey/ngx-quill/issues/1085>, or unsubscribe

**Comment by KillerCodeMonkey** [comment]
support has landed in v13
