### ISSUE TITLE
Compilation error - `quill 1.3.x` not compatible with `@types/quill 2.0.x`

### ISSUE THREAD

**Issue by khaldi-yass** [KillerCodeMonkey/ngx-quill#1092]
Hello sir, I face an error during project compilation after installing ngx-quill:

### Error
```bash
Error: node_modules/ngx-quill/lib/quill-editor.component.d.ts:3:21 - error TS2614: Module '"../../@types/quill"' has no exported member 'Delta'. Did you mean to use 'import Delta from "../../@types/quill"' instead?

3 import QuillType, { Delta } from 'quill';
```

### My "package.json" dependencies

```json
  "dependencies": {
    "@angular/animations": "~11.0.0",
    "@angular/common": "~11.0.0",
    "@angular/compiler": "~11.0.0",
    "@angular/core": "~11.0.0",
    "@angular/forms": "~11.0.0",
    "@angular/platform-browser": "~11.0.0",
    "@angular/platform-browser-dynamic": "~11.0.0",
    "@angular/router": "~11.0.0",
    "@fortawesome/fontawesome-free": "^5.15.1",
    "@types/quill": "^2.0.4",
    "animate.css": "^4.1.1",
    "bootstrap": "^4.5.3",
    "hover.css": "^2.3.2",
    "jquery": "^3.5.1",
    "ngx-quill": "^13.0.1",
    "popper.js": "^1.16.1",
    "quill": "^1.3.7",
    "quill-emoji": "^0.1.8",
    "rxjs": "~6.6.0",
    "tslib": "^2.0.0",
    "zone.js": "~0.10.2"
  }
```

Thank you in advance for your contribution.

**Comment by KillerCodeMonkey** [comment]
Use the issue search please. You are using The wrong typings. You have to
Install v 1.3.x for quilljs 1.3.x


Am 28.11.2020 in 20:33, Yassir KHALDI <notifications@github.com> schrieb:

Hello sir, I face an error during project compilation after installing
ngx-quill:
Error

Error: node_modules/ngx-quill/lib/quill-editor.component.d.ts:3:21 -
error TS2614: Module '"../../@types/quill"' has no exported member
'Delta'. Did you mean to use 'import Delta from "../../@types/quill"'
instead?

3 import QuillType, { Delta } from 'quill';

package.json Dependencies

  "dependencies": {
    "@angular/animations": "~11.0.0",
    "@angular/common": "~11.0.0",
    "@angular/compiler": "~11.0.0",
    "@angular/core": "~11.0.0",
    "@angular/forms": "~11.0.0",
    "@angular/platform-browser": "~11.0.0",
    "@angular/platform-browser-dynamic": "~11.0.0",
    "@angular/router": "~11.0.0",
    "@fortawesome/fontawesome-free": "^5.15.1",
    "@types/quill": "^2.0.4",
    "animate.css": "^4.1.1",
    "bootstrap": "^4.5.3",
    "hover.css": "^2.3.2",
    "jquery": "^3.5.1",
    "ngx-quill": "^13.0.1",
    "popper.js": "^1.16.1",
    "quill": "^1.3.7",
    "quill-emoji": "^0.1.8",
    "rxjs": "~6.6.0",
    "tslib": "^2.0.0",
    "zone.js": "~0.10.2"
  }

Thank you in advance for your contribution.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/KillerCodeMonkey/ngx-quill/issues/1092>, or unsubscribe

**Comment by khaldi-yass** [comment]
Thank you! it works like charm after using the version 1.3.7 of @types/quill.

The latest version of quill on npm is still `1.3.7` (while the 2.0 version is labeled `quill-2.0-dev`), but the typings are already updated to 2.0, that's what made some things confusing, I will update the issue title to make it easier to spot.
