### ISSUE TITLE
Angular Test suite failed to run: TypeError: Cannot read property 'imports' of undefined

### ISSUE THREAD

**Issue by nullptrerror** [KillerCodeMonkey/ngx-quill#1102]
I have a file called quillConfigMultimedia with the following:

```
import Quill from 'quill';
import { ImageResize } from 'quill-image-resize-module';
Quill.register('modules/imageResize', ImageResize);

export const quillConfigMultimedia = {
  modules: {
    toolbar: [
      ['bold', 'italic', 'underline', 'strike'], // toggled buttons
      [{ list: 'ordered' }, { list: 'bullet' }],
      [{ script: 'sub' }, { script: 'super' }], // superscript/subscript
      [{ indent: '-1' }, { indent: '+1' }], // outdent/indent
      [{ size: ['10px', false, '18px', '32px'] }], // custom dropdown
      [{ color: [] }, { background: [] }], // dropdown with defaults from theme
      [{ align: [] }],
      ['clean'], // remove formatting button
      ['link', 'image', 'video'], // link and image, video
    ],
    imageResize: {},
  },
  theme: 'snow',
};
```

When my test runs I get the following error.

![image](https://user-images.githubusercontent.com/59756494/101508170-55cda800-3945-11eb-8611-39838da8afd2.png)

My component with failing test:
![image](https://user-images.githubusercontent.com/59756494/101508883-2e2b0f80-3946-11eb-867d-4728f372a3f9.png)

**Comment by KillerCodeMonkey** [comment]
Since IT IS failing within The Image resize Module i would say this Problem
hast nothing to do with ngx-quill ;-).

Just correctly mock this Module or make Sure your test environment is
correctly Set up


Am 08.12.2020 in 17:10, nullptrerror <notifications@github.com> schrieb:

I have a file called quillConfigMultimedia with the following:

import Quill from 'quill';
import { ImageResize } from 'quill-image-resize-module';
Quill.register('modules/imageResize', ImageResize);

export const quillConfigMultimedia = {
  modules: {
    toolbar: [
      ['bold', 'italic', 'underline', 'strike'], // toggled buttons
      [{ list: 'ordered' }, { list: 'bullet' }],
      [{ script: 'sub' }, { script: 'super' }], // superscript/subscript
      [{ indent: '-1' }, { indent: '+1' }], // outdent/indent
      [{ size: ['10px', false, '18px', '32px'] }], // custom dropdown
      [{ color: [] }, { background: [] }], // dropdown with defaults from theme
      [{ align: [] }],
      ['clean'], // remove formatting button
      ['link', 'image', 'video'], // link and image, video
    ],
    imageResize: {},
  },
  theme: 'snow',
};

When my test runs I get the following error.

[image: image]
<https://user-images.githubusercontent.com/59756494/101508170-55cda800-3945-11eb-8611-39838da8afd2.png>

My component with failing test:
[image: image]
<https://user-images.githubusercontent.com/59756494/101508614-e5735680-3945-11eb-970c-4913ab6fd611.png>

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/KillerCodeMonkey/ngx-quill/issues/1102>, or unsubscribe

**Comment by nullptrerror** [comment]
quill-image-resize-module or user configuration issue not an ngx-quill issue.
