### ISSUE TITLE
Module '"../../@types/quill"' has no exported member 'Delta 

### ISSUE THREAD

**Issue by eng-dibo** [KillerCodeMonkey/ngx-quill#1107]
I installed `quill`, `@types/quill` and `ngx-quill` in my Angular 10 project.

but it gives me the following error
```
ERROR in ../../node_modules/ngx-quill/lib/quill-editor.component.d.ts:3:21
 - error TS2614: Module '"../../@types/quill"' has no exported member 'Delta'. 
Did you mean to use 'import Delta from "../../@types/quill"' instead?

3 import QuillType, { Delta } from 'quill';
```

also I installed `quill-delta`, and the is no `@types/quill-delta` in npm registry. 

installed versions:
ngx-quill: 12.0.1 (requires quill v1.3.7)
quill: 1.3.7
quill-delta: 4.2.2
@types/quill: 2.0.4

**Comment by KillerCodeMonkey** [comment]
please guys use the issue search... like semantic versioning is used... if you install quilljs 1.x you need the typings of quilljs in the version 1.x

**Comment by eng-dibo** [comment]
fixed by installing `@types/quill` with the exact version as `quill`, i.e: v1.3.7

**Comment by kfirufk** [comment]
quill 2 is not supported ? 
if I install     "@types/quill": "^2.0.4" and "quill": "2.0.0-dev.4" I get the same error.

**Comment by KillerCodeMonkey** [comment]
Nope i Just Support stable quill Versions.

You could try to use quill 2 dev4 but with old typings


Am 03.01.2021 in 10:21, Kfir Ozer <notifications@github.com> schrieb:

quill 2 is not supported ?
if I install "@types/quill": "^2.0.4" and "quill": "2.0.0-dev.4" I get the
same error.

—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub
<https://github.com/KillerCodeMonkey/ngx-quill/issues/1107#issuecomment-753589470>,
or unsubscribe

**Comment by santiagopuentep** [comment]
You can import the quill Delta types using `import type Delta from "quill/node_modules/quill-delta/dist/Delta";`
