### ISSUE TITLE
[(ngModel)] not binding the data property coming from database through an api call

### ISSUE THREAD

**Issue by pradeepjanga** [KillerCodeMonkey/ngx-quill#1122]
we are using Angular10 with   "ngx-quill": "^12.0.1" in package.json
when i type in the editor it is binding and able to persist the data but when data coming back from an api call from backend it is not able to bind the data into ngModel 2way binding. But this used to work before on angular 8 and we recently upgraded to angular 10 and updated to latest ngx-quill 2.0.1 and it is not working as expected.
Below is how am using the quill-editor and this used to work with angular 8.

```
<quill-editor #body name="body" id="body" **[(ngModel)]="currentNotification().messageText"** (onSelectionChanged)="editorSelectionChanged($event)" (onEditorCreated)="editorCreated($event)"
              (onContentChanged)="contentChanged($event)"  [style]="{height: '250px', background: 'white'}">
            
              <div id="toolbar-container"  quill-editor-toolbar>                
                 <!-- Text Size  -->
                <span class="ql-formats">
                  <select class="ql-font"></select>
                  <select class="ql-size"></select>
                </span>
                <!-- Text Formatting  -->
                <span class="ql-formats">
                  <button class="ql-bold"></button>
                  <button class="ql-italic"></button>
                  <button class="ql-underline"></button>
                  <button class="ql-strike"></button>
                </span>
                <span class="ql-formats">
                  <select class="ql-color"></select>
                  <select class="ql-background"></select>
                </span>
                  <!-- Subscript/superscript  -->
                <span class="ql-formats">
                  <button class="ql-script" value="sub"></button>
                  <button class="ql-script" value="super"></button>
                </span>
                <!-- Text Block format -->
                   <!-- Header Sizes  -->
                <span class="ql-formats">
                  <button class="ql-header" value="1"></button>
                  <button class="ql-header" value="2"></button>
                  <!-- <button class="ql-blockquote"></button>
                  <button class="ql-code-block"></button> -->
                </span>
                 <!-- Ordered List / Bullets   -->
                  <!--  Indenting -->
                <span class="ql-formats">
                  <button class="ql-list" value="ordered"></button>
                  <!-- <button class="ql-list" value="bullet"></button> -->
                  <button class="ql-indent" value="-1"></button>
                  <button class="ql-indent" value="+1"></button>
                </span>
               <span class="ql-formats">
                 <!--   <button class="ql-direction" value="rtl"></button> -->
                  <select class="ql-align"></select>
                </span>
                <span class="ql-formats">
                  <button class="ql-link"></button>
                  <button class="ql-image"></button>
                  <button class="ql-video"></button>
                  <!-- <button class="ql-formula"></button> -->
                </span>
                <!-- <span class="ql-formats">
                  <button class="ql-clean"></button>
                </span> -->
              </div>
           
            </quill-editor>
```

**Comment by KillerCodeMonkey** [comment]
You cannot bind The result of a function call to the ngmodel. Just Store IT
to a class property and then you get the updated value.


Am 30.12.2020 in 17:17, pradeepjanga <notifications@github.com> schrieb:

we are using Angular10 with "ngx-quill": "^12.0.1" in package.json
when i type in the editor it is binding and able to persist the data but
when data coming back from an api call from backend it is not able to bind
the data into ngModel 2way binding. But this used to work before on angular
8 and we recently upgraded to angular 10 and updated to latest ngx-quill
2.0.1 and it is not working as expected.
Below is how am using the quill-editor and this used to work with angular 8.

<quill-editor #body name="body" id="body"
*[(ngModel)]="currentNotification().messageText"*
(onSelectionChanged)="editorSelectionChanged($event)"
(onEditorCreated)="editorCreated($event)"
(onContentChanged)="contentChanged($event)" [style]="{height: '250px',
background: 'white'}">

          <div id="toolbar-container"  quill-editor-toolbar>
             
            <span class="ql-formats">
              <select class="ql-font"></select>
              <select class="ql-size"></select>





            </span>
            
            <span class="ql-formats">
              <button class="ql-bold"></button>
              <button class="ql-italic"></button>
              <button class="ql-underline"></button>
              <button class="ql-strike"></button>
            </span>
            <span class="ql-formats">
              <select class="ql-color"></select>
              <select class="ql-background"></select>
            </span>
              
            <span class="ql-formats">
              <button class="ql-script" value="sub"></button>
              <button class="ql-script" value="super"></button>
            </span>
            
               
            <span class="ql-formats">
              <button class="ql-header" value="1"></button>
              <button class="ql-header" value="2"></button>
              
            </span>
             
              
            <span class="ql-formats">
              <button class="ql-list" value="ordered"></button>
              
              <button class="ql-indent" value="-1"></button>
              <button class="ql-indent" value="+1"></button>
            </span>
           <span class="ql-formats">
             
              <select class="ql-align"></select>
            </span>
            <span class="ql-formats">
              <button class="ql-link"></button>
              <button class="ql-image"></button>
              <button class="ql-video"></button>
              
            </span>
            
          </div>

        </quill-editor>

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/KillerCodeMonkey/ngx-quill/issues/1122>, or unsubscribe

**Comment by pradeepjanga** [comment]
I tried to display a simple text but it is not.

html code:
 ```
           <quill-editor #body name="body" id="body" [(ngModel)]="messageText" (onSelectionChanged)="editorSelectionChanged($event)" (onEditorCreated)="editorCreated($event)"
              (onContentChanged)="contentChanged($event)"  [style]="{height: '250px', background: 'white'}">
```

ts file:
 messageText: string = "This is Test message";

**Comment by KillerCodeMonkey** [comment]
Just Checkout my Demo repo. There are many working examples. Even Very
simple with Just ngModel setting a simple String


Am 30.12.2020 in 19:31, pradeepjanga <notifications@github.com> schrieb:

I tried to display a simple text but it is not.

html code:

          <quill-editor #body name="body" id="body"
[(ngModel)]="messageText"
(onSelectionChanged)="editorSelectionChanged($event)"
(onEditorCreated)="editorCreated($event)"
             (onContentChanged)="contentChanged($event)"
[style]="{height: '250px', background: 'white'}">

ts file:
messageText: string = "This is Test message";

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/KillerCodeMonkey/ngx-quill/issues/1122#issuecomment-752717045>,
or unsubscribe

**Comment by pradeepjanga** [comment]
my messageText contains text like below:

`<p>Study Schema Event Label is %SSEL and last name is %LN.</p><p>%GVV is GF valid value and</p><p>%GFV is GF variable.</p><p><br></p><p>Birth: %B</p><p>Reg date: %RD</p><p>Race: %R;</p`

will that work ?

**Comment by pradeepjanga** [comment]
am using <p> and where can i change the quill configuration for that ??

**Comment by pradeepjanga** [comment]
I found the issue where it is not displaying text.
Below is the block of code causing the message text not to display on the quill editor.
this.renderer.selectRootElement(.ql-editor) is causing something.
is (OnEditorCreated) event chagned ???

.html file:

 ```
<quill-editor #body name="body" id="body" [(ngModel)]="studyNotification.messageText" (onSelectionChanged)="editorSelectionChanged($event)"
             **(onEditorCreated)="editorCreated($event)"** [style]="{height: '250px', background: 'white'}">
```
```

editorCreated(editorInstance) {
    this.editorInstance = editorInstance;
    **this.editorElem = this.renderer.selectRootElement('.ql-editor');**
  }


```

**Comment by pradeepjanga** [comment]
If i commen out the below of code , it is working. Not sure what that piece of code is doing.

**Comment by KillerCodeMonkey** [comment]
do not know maybe is angular manipulating the dom node so it is not usable for quilljs anymore.

you can just grab the root node of the editor from the editorInstance -> there is a property `root` on it.
