### ISSUE TITLE
Error with debounceTime and delta data

### ISSUE THREAD

**Issue by Marius-Romanus** [KillerCodeMonkey/ngx-quill#1125]
Hi, I'm trying to put a little delay in quilljs so as not to send so much data to the server. I'm using debounceTime and subscribe, but the delta it provides using this method is only the last letter. So I can't use updateContents in another terminal.

```
@ViewChild('editor', { static: true }) quillEditorComponent: QuillEditorComponent;

this.quillEditorComponent.onContentChanged
      .pipe(
        debounceTime(250),
        distinctUntilChanged()
      )
      .subscribe((event: ContentChange) => {
        console.log(event)
        // content -> OK
        // delta -> KO, only the last letter
        // editor -> OK
        // html -> OK
        // oldDelta -> OK
        // source -> OK
        // text -> OK
});

```
I don't know if it has to do with this, but when I use updateContents it is inserting a newline (carriage return and line feed "\n"), when the delta only contains this, for example:
```
delta: {
  ops: [
    {retain: 2},
    {insert: "a"}
  ]
}
```
Thanks a lot and good job!

**Comment by KillerCodeMonkey** [comment]
Delta is containing the Last Things that where inserted in The Editor.

OnContentChanged is Just a wrapper for The native quilljs Text-Change Event
+ adds The current content and Editor to The Event Data. Debouncing and
getting all The Changes Will Not Work.

But you could use The "content" and Work with IT.

In General i would use a formControl and subscribing dir Changes + debounce.

PS:

Quilljs adds an empty Line after The content If you Set it. This is how
quilljs works.

So this is Not an Error Just The expected way IT IS working.

Am 02.01.2021 in 15:22, Marius-Romanus <notifications@github.com> schrieb:

Hi, I'm trying to put a little delay in quilljs so as not to send so much
data to the server. I'm using debounceTime and subscribe, but the delta it
provides using this method is only the last letter. So I can't use
updateContents in another terminal.

@ViewChild('editor', { static: true }) quillEditorComponent:
QuillEditorComponent;

this.quillEditorComponent.onContentChanged
      .pipe(
        debounceTime(250),
        distinctUntilChanged()
      )
      .subscribe((event: ContentChange) => {
        console.log(event)
        // content -> OK
        // delta -> KO, only the last letter
        // editor -> OK
        // html -> OK
        // oldDelta -> OK
        // source -> OK
        // text -> OK
});


I don't know if it has to do with this, but when I use updateContents it is
inserting a newline (carriage return and line feed "\n"), when the delta
only contains this, for example:

delta: {
  ops: [
    {retain: 2},
    {insert: "a"}
  ]
}

Thanks a lot and good job!

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/KillerCodeMonkey/ngx-quill/issues/1125>, or unsubscribe

**Comment by Marius-Romanus** [comment]
How fast! :)
I think that what you comment is not worth me, since I do not get the delta, only the text, and the changes do not appear when, for example, I underline the text.
Do you mean this or am I wrong?

`<quill-editor [formControl]="formControlEditor"></quill-editor>`

```
formControlEditor = new FormControl();
this.formControlEditor.valueChanges
    .pipe(
      debounceTime(250),
      distinctUntilChanged()
    )
    .subscribe(event => {
      console.log(event)
});
```
Thanks again

**Comment by KillerCodeMonkey** [comment]
Yes i mean this :)


Am 02.01.2021 in 16:06, Marius-Romanus <notifications@github.com> schrieb:

How fast! :)
I think that what you comment is not worth me, since I do not get the
delta, only the text, and the changes do not appear when, for example, I
underline the text.
Do you mean this or am I wrong?

<quill-editor [formControl]="formControlEditor"></quill-editor>

formControlEditor = new FormControl();
this.formControlEditor.valueChanges
    .pipe(
      debounceTime(250),
      distinctUntilChanged()
    )
    .subscribe(event => {
      console.log(event)
});

Thanks again

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/KillerCodeMonkey/ngx-quill/issues/1125#issuecomment-753484431>,
or unsubscribe

**Comment by Marius-Romanus** [comment]
ok, I guess I'll end up removing the debounceTime so that it takes everything without problems, greetings
