### ISSUE TITLE
default buttons actions in custom toolbar

### ISSUE THREAD

**Issue by kernyden** [KillerCodeMonkey/ngx-quill#1171]
Hi, try to ask you on examples: 
```
<div quill-editor-toolbar>
    <select class="ql-color" [title]="'Color'"></select> //wrapped and do the actions 
    <div class="ql-my-custom-container"></div //customized component
    <span class="ql-formats">
      <button class="ql-link"></button> //how to make this works?
    </span>
    <span class="ql-formats">
      <button class="ql-bold"></button>//how to make this works?
    </span>
 </div>
```

I want to use a mix of custom and default functionallity without adding unnecessary code from <code>ngx-quill</code>. Is it possible? If not, what do i have to use (mean <code>(click)="editor.foo($event)"</code>)? (i didn't use this custom functionallity before, been used <code>[modules]="modules"</code>)

ahh, sorry
```
<button class="ql-bold" value="bold">
```

**Comment by KillerCodeMonkey** [comment]
Since the toolbar ist used by quilljs add some good old and native js
Eventlisteners in those Buttons


Am 18.02.2021 in 15:36, kernyden <notifications@github.com> schrieb:

Hi, try to ask you on examples:

<div quill-editor-toolbar>
    <select class="ql-color" [title]="'Color'"></select> //wrapped and
do the actions
    <div class="ql-my-custom-container"></div //customized component
    <span class="ql-formats">
      <button class="ql-link"></button> //how to make this works?
    </span>
    <span class="ql-formats">
      <button class="ql-bold"></button>//how to make this works?
    </span>
 </div>

I want to use a mix of custom and default functionallity without adding
unnecessary code from ngx-quill. Is it possible? If not, what do i have to
use (mean (click)="editor.foo($event)")? (i didn't use this custom
functionallity before, been used [modules]="modules")

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/KillerCodeMonkey/ngx-quill/issues/1171>, or unsubscribe
