### ISSUE TITLE
Quill View  performance issue

### ISSUE THREAD

**Issue by dine-mathi** [KillerCodeMonkey/ngx-quill#1175]
If I use quill view inside ngFor to display around 100 records, then it takes few seconds(~2sec) to display the data on the browser. I store the formatted data as JSON. 

Is there any way to improve the performance? I will be using only the basic formatting shown in image below.

![image](https://user-images.githubusercontent.com/37948307/108501309-20472280-72d7-11eb-8668-453823da4dae.png)

I have created a sample project to test the performance of quill view for 100 records using JSON format.
https://github.com/dine-mathi/POC

Steps to find the performance issue:
1.  Run the application and click on any of the item in the item list.
2. Now click on 'Back to List' link in item page. It will take around 2 seconds to render the list page.

In the sample the content per item is small, in cases where the content is slightly higher(around 250 characters) then it takes around 4 to 6 seconds to display the page.

Any help is highly appreciated!

**Comment by KillerCodeMonkey** [comment]
This is More Like an issue of quilljs.

Quillview component is using a Full quilleditor to Render The content. If
you use 100 or More of Them IT IS The expected result.

Each instance is doing some heavy Dom manipulation and so on.

If you really Need to Render such an amount build your own solution or
Checkout some Serverside renderer for quilljs to get the HTML Strings and
use The quill-view-html component.

A custom solution could be: instantiate one Hidden native quill Editor.
Loop over your entries - Pass The content to quill instance and read The
HTML respresentation.

So you would have a longer initialisation time but faster working with The
Elements.


Am 19.02.2021 in 14:21, Dinesh Mathivanan <notifications@github.com>
schrieb:

If I use quill view inside ngFor to display around 100 records, then it
takes few seconds(~2sec) to display the data on the browser. I store the
formatted data as JSON.

Is there any way to improve the performance? I will be using only the basic
formatting shown in image below.

[image: image]
<https://user-images.githubusercontent.com/37948307/108501309-20472280-72d7-11eb-8668-453823da4dae.png>

I have created a sample project to test the performance of quill view for
100 records using JSON format.
https://github.com/dine-mathi/POC

Steps to find the performance issue:

   1. Run the application and click on any of the item in the item list.
   2. Now click on 'Back to List' link in item page. It will take around 2
   seconds to render the list page.

In the sample the content per item is small, in cases where the content is
slightly higher(around 250 characters) then it takes around 4 to 6 seconds
to display the page.

Any help is highly appreciated!

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/KillerCodeMonkey/ngx-quill/issues/1175>, or unsubscribe
