### ISSUE TITLE
Whitespaces cannot be inserted at the end of the line in Mozilla, Angular 11

### ISSUE THREAD

**Issue by kryogenyk** [KillerCodeMonkey/ngx-quill#1181]
I'm running the same packages versions as the example:
@types/quill: 1.3.10
ngx-quill: 13.2.0
quill: 1.3.7

What happens is that when I reach the end of a line, inserting a space and another letter, afterwards, removes the whitespace and sticks the letter to the last character written.

On .ql-editor white-space is set to pre-wrap.

From searching for differences, your example produces div elements when inserting text, while mine produces paragraphs.

[In this working stackblitz](https://stackblitz.com/edit/angular-7taovk?file=src/app/app.component.ts)  paragraph elements are also inserted inside the DOM, and whitespaces work at the end of the line. 

Also, it also works on Chrome, locally.

**Comment by KillerCodeMonkey** [comment]
So it does not Work in your Project, but everywhere Else?

**Comment by kryogenyk** [comment]
Exactly, and I'm trying to find where does this issue come from.

What is the expected behavior of ngx-quill? Should it insert divs or paragraphs?
If divs is the answer, why does it behave differently in my project? Could it be something related to some config / settings / environment?

**Comment by KillerCodeMonkey** [comment]
The expected behaviour is, that IT is working Like native quilljs.

Ngx-quill is Not doing anything Special. So it should work Out of the Box.

Maybe you are using some custom validators or anything Else ?


Am 22.02.2021 in 17:26, kryogenyk <notifications@github.com> schrieb:

Exactly, and I'm trying to find where does this issue come from.

What is the expected behavior of ngx-quill? Should it insert divs or
paragraphs?
If divs is the answer, why does it behave differently in my project? Could
it be something related to some config / settings / environment?

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/KillerCodeMonkey/ngx-quill/issues/1181#issuecomment-783496791>,
or unsubscribe

**Comment by kryogenyk** [comment]
My project did not have any additional things that might have affected ngx-quill's behavior, except the fact that the module was being lazily loaded. I even tried to display the editor after the view init, yet nothing changed. I found the solution in another completed issue [https://github.com/KillerCodeMonkey/ngx-quill/issues/11](https://github.com/KillerCodeMonkey/ngx-quill/issues/11) from here, when trying to change the paragraphs inserted by quill to divs.
