### ISSUE TITLE
[BUG] Sanitize removes inline styling

### ISSUE THREAD

**Issue by 99diagha** [KillerCodeMonkey/ngx-quill#1200]
Since my comment about this went unresponded in [this](https://github.com/KillerCodeMonkey/ngx-quill/issues/232#issuecomment-808715016) thread, I'll open an issue for it. It's crucial for something I am building and I'll appreciate any guidance or solutions that could fix this.

You can find an example for this bug [here](https://stackblitz.com/edit/angular-markdown-editor-jira-czexb3?file=src/app/app.component.ts). If you scroll down, you'll see that the colors are not working.

Using following versions.
`quill: 1.3.7`
`ngx-quill: 11.1.0`

**Comment by KillerCodeMonkey** [comment]
This is Not a Bug again. I Just use angulars sanatizing. If angular Strips
IT, i will and can Not Change it ;-).

If you find a way to configure it let me know or create a PR. Thx


Am 28.03.2021 in 21:53, Diar Kourehpaz ***@***.***> schrieb:

Since my comment about this went unresponded in this
<https://github.com/KillerCodeMonkey/ngx-quill/issues/232#issuecomment-808715016>
thread, I'll open an issue for it. It's crucial for something I am building
and I'll appreciate any guidance or solutions that could fix this.

You can find an example for this bug here
<https://stackblitz.com/edit/angular-markdown-editor-jira-czexb3?file=src/app/app.component.ts>.
If you scroll down, you'll see that the colors are not working.

Using following versions.
quill: 1.3.7
ngx-quill: 11.1.0

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/KillerCodeMonkey/ngx-quill/issues/1200>, or unsubscribe

**Comment by KillerCodeMonkey** [comment]
An per Default stripping Styling per Default is good approach to void xss.
Check The angular Docs about IT.


Am 28.03.2021 in 21:53, Diar Kourehpaz ***@***.***> schrieb:

Since my comment about this went unresponded in this
<https://github.com/KillerCodeMonkey/ngx-quill/issues/232#issuecomment-808715016>
thread, I'll open an issue for it. It's crucial for something I am building
and I'll appreciate any guidance or solutions that could fix this.

You can find an example for this bug here
<https://stackblitz.com/edit/angular-markdown-editor-jira-czexb3?file=src/app/app.component.ts>.
If you scroll down, you'll see that the colors are not working.

Using following versions.
quill: 1.3.7
ngx-quill: 11.1.0

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/KillerCodeMonkey/ngx-quill/issues/1200>, or unsubscribe

**Comment by 99diagha** [comment]
@KillerCodeMonkey Oh, I see. I'll update this thread or open a PR if I find a fix. Thanks for responding!

**Comment by KillerCodeMonkey** [comment]
Btw you can Just try to use domsanitizer to Bypass trust Stylings in your
HTML String before passing IT to ngx-quill.



Am 28.03.2021 in 21:53, Diar Kourehpaz ***@***.***> schrieb:

Since my comment about this went unresponded in this
<https://github.com/KillerCodeMonkey/ngx-quill/issues/232#issuecomment-808715016>
thread, I'll open an issue for it. It's crucial for something I am building
and I'll appreciate any guidance or solutions that could fix this.

You can find an example for this bug here
<https://stackblitz.com/edit/angular-markdown-editor-jira-czexb3?file=src/app/app.component.ts>.
If you scroll down, you'll see that the colors are not working.

Using following versions.
quill: 1.3.7
ngx-quill: 11.1.0

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/KillerCodeMonkey/ngx-quill/issues/1200>, or unsubscribe
