### ISSUE TITLE
pass html issue.

### ISSUE THREAD

**Issue by GiorgiKhmaladze** [KillerCodeMonkey/ngx-quill#1204]
Hey, hope you are doing well.
I have form control with value '<span class="test">test</span>'
And inside editor I can see that text is wrapped inside p tag.
So if I have very big HTML which has some classes and other elements, is it possible to keep this HTML and continue editing it?
I can see quill-view-html but it's not editable.

Thanks!

**Comment by KillerCodeMonkey** [comment]
If your HTML is quilljs compatible yes. Otherwise no.

You can only use allowed Tags and classes quilljs Supports.

Thats a reason quilljs is Not a HTML Editor ;-)


Am 30.03.2021 in 20:53, GiorgiKhmaladze ***@***.***> schrieb:

Hey, hope you are doing well.
I have form control with value 'test'
And inside editor I can see that text is wrapped inside p tag.
So if I have very big HTML which has some classes and other elements, is it
possible to keep this HTML and continue editing it ?
I can see quill-view-html but it's not editable.

Thanks!

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/KillerCodeMonkey/ngx-quill/issues/1204>, or unsubscribe
