### ISSUE TITLE
'quill-editor' is not a known element

### ISSUE THREAD

**Issue by XxQuickSilverZz** [KillerCodeMonkey/ngx-quill#1208]
![image](https://user-images.githubusercontent.com/55958378/113589981-585db700-9632-11eb-9620-b513c9c7b849.png)

I got this error when i try to add Quill to my Angular project. 

I use a Lazy Child Module. 

AppModule
imports:  [QuillModule.forRoot()],

@NgModule({
  declarations: [NewsListComponent, AddEditNewsComponent],
  imports: [CommonModule, SharedModule, NewsRoutingModule, QuillModule],
  exports: [NewsListComponent],
  providers: [],
  schemas: [NO_ERRORS_SCHEMA],
})

done all of your installation points

npm install ngx-quill
for projects using Angular < v5.0.0 install npm install ngx-quill@1.6.0
install @angular/core, @angular/common, @angular/forms, @angular/platform-browser, quill v1.x, @types/quill v1.x and rxjs - peer dependencies of ngx-quill
include theme stylings: bubble.css, snow.css and core.css of quilljs in your index.html (you can find them in node_modules/quill/dist), or add them in your css/scss files with @import statements, or add them external stylings in your build process.
Example at the beginning of your style.(s)css:
 @import '~quill/dist/quill.core.css';
 @import '~quill/dist/quill.bubble.css';
 @import '~quill/dist/quill.snow.css';

package.json
    "@types/quill": "^2.0.6",
    "ngx-quill": "^13.2.0",
    "quill": "^1.3.7",

angular.json not touched.

**Comment by KillerCodeMonkey** [comment]
It is working in my Demo repo. There is a child Module example.

Btw. For quilljs 1.x you have to Install typings for v1. So you have to use
@types/quill v1.x


Am 05.04.2021 in 17:33, QuickSilver ***@***.***> schrieb:

[image: image]
<https://user-images.githubusercontent.com/55958378/113589981-585db700-9632-11eb-9620-b513c9c7b849.png>

I got this error when i try to add Quill to my Angular project.

I use a Lazy Child Module.

AppModule
imports: [QuillModule.forRoot()],

@NgModule <https://github.com/NgModule>({
declarations: [NewsListComponent, AddEditNewsComponent],
imports: [CommonModule, SharedModule, NewsRoutingModule, QuillModule],
exports: [NewsListComponent],
providers: [],
schemas: [NO_ERRORS_SCHEMA],
})

done all of your installation points

npm install ngx-quill
for projects using Angular < v5.0.0 install npm install ***@***.***
install @angular/core, @angular/common, @angular/forms,
@angular/platform-browser, quill v1.x, @types/quill v1.x and rxjs - peer
dependencies of ngx-quill
include theme stylings: bubble.css, snow.css and core.css of quilljs in
your index.html (you can find them in node_modules/quill/dist), or add them
in your css/scss files with @import <https://github.com/import> statements,
or add them external stylings in your build process.
Example at the beginning of your style.(s)css:
@import <https://github.com/import> '~quill/dist/quill.core.css';
@import <https://github.com/import> '~quill/dist/quill.bubble.css';
@import <https://github.com/import> '~quill/dist/quill.snow.css';

package.json
***@***.***/quill": "^2.0.6",
"ngx-quill": "^13.2.0",
"quill": "^1.3.7",

angular.json not touched.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/KillerCodeMonkey/ngx-quill/issues/1208>, or unsubscribe

**Comment by XxQuickSilverZz** [comment]
Now:
    "@types/quill": "^1.3.7",
    "quill": "^1.3.7",

Still same error.
I have checked your demo https://killercodemonkey.github.io/ngx-quill-example/#html 
but its equal to my structure.

**Comment by KillerCodeMonkey** [comment]
And when you Clone or Download The Demo repo + Run yarn Install and start
it.doey IT Work?

Which angular Version do you use?


Am 05.04.2021 in 18:04, QuickSilver ***@***.***> schrieb:

Now:
***@***.***/quill": "^1.3.7",
"quill": "^1.3.7",

Still same error.
I have checked your demo
https://killercodemonkey.github.io/ngx-quill-example/#html
but its equal to my structure.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/KillerCodeMonkey/ngx-quill/issues/1208#issuecomment-813473323>,
or unsubscribe

**Comment by XxQuickSilverZz** [comment]
I use Angular 11.0.9. I now you will be work. But i dont know why my setup is wrong. I have follwed your installation steps.

**Comment by KillerCodeMonkey** [comment]
Maybe you missed to add quillmodule to some child Modules.

Maybe build something like a Stackblitz for reproduction


Am 05.04.2021 in 17:33, QuickSilver ***@***.***> schrieb:

[image: image]
<https://user-images.githubusercontent.com/55958378/113589981-585db700-9632-11eb-9620-b513c9c7b849.png>

I got this error when i try to add Quill to my Angular project.

I use a Lazy Child Module.

AppModule
imports: [QuillModule.forRoot()],

@NgModule <https://github.com/NgModule>({
declarations: [NewsListComponent, AddEditNewsComponent],
imports: [CommonModule, SharedModule, NewsRoutingModule, QuillModule],
exports: [NewsListComponent],
providers: [],
schemas: [NO_ERRORS_SCHEMA],
})

done all of your installation points

npm install ngx-quill
for projects using Angular < v5.0.0 install npm install ***@***.***
install @angular/core, @angular/common, @angular/forms,
@angular/platform-browser, quill v1.x, @types/quill v1.x and rxjs - peer
dependencies of ngx-quill
include theme stylings: bubble.css, snow.css and core.css of quilljs in
your index.html (you can find them in node_modules/quill/dist), or add them
in your css/scss files with @import <https://github.com/import> statements,
or add them external stylings in your build process.
Example at the beginning of your style.(s)css:
@import <https://github.com/import> '~quill/dist/quill.core.css';
@import <https://github.com/import> '~quill/dist/quill.bubble.css';
@import <https://github.com/import> '~quill/dist/quill.snow.css';

package.json
***@***.***/quill": "^2.0.6",
"ngx-quill": "^13.2.0",
"quill": "^1.3.7",

angular.json not touched.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/KillerCodeMonkey/ngx-quill/issues/1208>, or unsubscribe

**Comment by XxQuickSilverZz** [comment]
In Child Module  
  imports: [CommonModule, SharedModule, NewsRoutingModule, **QuillModule**]

**Comment by KillerCodeMonkey** [comment]
And The Modules connecting with a Route where ngx-quill is used have
quillmodule AS well as import?


Am 05.04.2021 in 18:21, QuickSilver ***@***.***> schrieb:

In Child Module
imports: [CommonModule, SharedModule, NewsRoutingModule, *QuillModule*]

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/KillerCodeMonkey/ngx-quill/issues/1208#issuecomment-813482875>,
or unsubscribe

**Comment by XxQuickSilverZz** [comment]
I only have 2 modules.
app.module.ts imports: [QuillModule.forRoot()]

and news.module.ts imports: [QuillModule]

both using 
import { QuillModule } from 'ngx-quill';

**Comment by KillerCodeMonkey** [comment]
Strange but without a repo or Stackblitz to reproduce. I can Not Help you


Am 05.04.2021 in 18:37, QuickSilver ***@***.***> schrieb:

I only have 2 modules.
app.module.ts imports: [QuillModule.forRoot()]

and news.module.ts imports: [QuillModule]

both using
import { QuillModule } from 'ngx-quill';

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/KillerCodeMonkey/ngx-quill/issues/1208#issuecomment-813491299>,
or unsubscribe

**Comment by XxQuickSilverZz** [comment]
i have given you access to my repo.

**Comment by KillerCodeMonkey** [comment]
Would be nice If you could Just create a Public minimal repo for
reproduction. I will Not debug private ones with Overhead.




Am 05.04.2021 in 18:54, QuickSilver ***@***.***> schrieb:

i have given you access to my repo.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/KillerCodeMonkey/ngx-quill/issues/1208#issuecomment-813501444>,
or unsubscribe

**Comment by XxQuickSilverZz** [comment]
Yeah its a small repo. its not really big no worries. Its a startup of a project!

**Comment by XxQuickSilverZz** [comment]
@KillerCodeMonkey What now can you help me?

**Comment by KillerCodeMonkey** [comment]
Since this is an Open Source projectl I will have a Look when i have time
for it ;-).

AS a fix you could Just Clone My Demo repo and use it AS a Base Project for
your App.

If it IS really urgent and is Not really a Bug or issue with ngx-quill, you
should create a Stack overflow thread and provide a Public repo so maybe
someone Else is faster to Help you.



Am 06.04.2021 in 21:54, QuickSilver ***@***.***> schrieb:

@KillerCodeMonkey <https://github.com/KillerCodeMonkey> What now can you
help me?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/KillerCodeMonkey/ngx-quill/issues/1208#issuecomment-814398083>,
or unsubscribe

**Comment by XxQuickSilverZz** [comment]
@KillerCodeMonkey the 'quill-editor' is not a known element error is gone now. But the Editor not displayed. :(

**Comment by XxQuickSilverZz** [comment]
Ok i will wait. I looked at your demo its really the same..

**Comment by XxQuickSilverZz** [comment]
it was a routing problem.  

{
        path: 'news',
        loadChildren: () =>
          import('./views/news/news.module').then((m) => m.NewsModule),
      },

is correct. I have imported the news.routing.module.ts this was not correct
