### ISSUE TITLE
Get text from editor

### ISSUE THREAD

**Issue by CesaragsUC** [KillerCodeMonkey/ngx-quill#1211]
hi, i new on this. I read the doc but i don't understand totally, i using in angular, i have a form that after i click in submit button, how i can read content text from editor? 

![image](https://user-images.githubusercontent.com/25139027/113925537-83c2dc00-97c1-11eb-8cf9-ab35f9e0aa38.png)

![image](https://user-images.githubusercontent.com/25139027/113925644-a7862200-97c1-11eb-9d1f-0c6913b9e41c.png)

sorry my english

**Comment by KillerCodeMonkey** [comment]
Then you should maybe Checkout some angular Tutorials about Forms. Ngmodel
for template driven and formControls for reactive Forms...

And If this Not helps Just use The Outputs/Events of the component
(documentated in The readme)

And If this is Not clear enough, Checkout The Linked advanced Demo repo to
get examples for Many usecases.


Am 07.04.2021 in 21:54, CesaragsUC ***@***.***> schrieb:

hi, i new on this. I read the doc but i don't understand totally, i using
in angular, i have a form that after i click in submit button, how i can
read content text from editor?

[image: image]
<https://user-images.githubusercontent.com/25139027/113925537-83c2dc00-97c1-11eb-8cf9-ab35f9e0aa38.png>

[image: image]
<https://user-images.githubusercontent.com/25139027/113925644-a7862200-97c1-11eb-9d1f-0c6913b9e41c.png>

sorry my english

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/KillerCodeMonkey/ngx-quill/issues/1211>, or unsubscribe

**Comment by CesaragsUC** [comment]
thx . i just got using Forms, work fine now.
btw this is amazing  text editor
