### ISSUE TITLE
Custom toolbar - hiding / showing buttons with display: none leads to weird behavior

### ISSUE THREAD

**Issue by AlexBerlo** [KillerCodeMonkey/ngx-quill#1222]
Hello !

I have a custom toolbar with a button which I use to hide/show quill editor button groups ( bold/italic/underline).
The issue is that after I set an option, lets say italic for example, and afterwards I hide the div with the button group, quill forgets the state.

Please see the issue reproducing here: https://stackblitz.com/edit/angular-ivy-dq54be?file=src/app/app.component.html
Thank you !

Edit: I've tried with visibility : hidden and I get the same behavior

**Comment by AlexBerlo** [comment]
It works when you turn it on the first time but afterwards it doesn't turn off. I'll have a video soon

**Comment by KillerCodeMonkey** [comment]
ah, but i think this is not an ngx-quill problem.

i would try to avoid using angular stuff in the quill-editor-toolbar, because this node is used internal by quilljs and quilljs does not know anything about angular.

so try your implementation with document.addEventListener + setting the styling/class with plain old javascript

**Comment by KillerCodeMonkey** [comment]
PS: quilljs is very strict so each format/toolbar button should have a css-class starting with "ql-".

maybe your custom button needs to have something similar like 'ql-formats'

**Comment by AlexBerlo** [comment]
Looks like you are right, it works with vanilla js
updated stackblitz: https://stackblitz.com/edit/angular-ivy-dq54be?file=src%2Fapp%2Fapp.component.html;
Thank you
