### ISSUE TITLE
Sticky Toolbar

### ISSUE THREAD

**Issue by mickdelaney** [KillerCodeMonkey/ngx-quill#1245]
Hi, 

Just wondering if was an easy way to make the toolbar remain sticky ?
Would help with long document authoring, instead of having to scroll back up to use the various buttons.

Thanks for the great work.

**Comment by KillerCodeMonkey** [comment]
Sure Just CSS. You can do what you want. Make IT Sticky :) or positionate
IT absolute.

By building a custom toolbar you can even add your own classes and dom
nodes.




Am 14.05.2021 in 10:53, mick delaney ***@***.***> schrieb:

Hi,

Just wondering if was an easy way to make the toolbar remain sticky ?
Would help with long document authoring, instead of having to scroll back
up to use the various buttons.

Thanks for the great work.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/KillerCodeMonkey/ngx-quill/issues/1245>, or unsubscribe

**Comment by mickdelaney** [comment]
Thanks
