### ISSUE TITLE
Double Click To Edit/Remove Image

### ISSUE THREAD

**Issue by tranhao167** [KillerCodeMonkey/ngx-quill#1246]
Hi guy,
How can double click to image which will have action to do something like view detail or remove this image

**Comment by KillerCodeMonkey** [comment]
That is Not possible with The default Image Blot.

Just add a custom Image Blot Implementation. Or more hacky - add a global
Clicklistener to all Images in The contentarea of the Editor.


Am 15.05.2021 in 08:15, Tran Hao ***@***.***> schrieb:

Hi guy,
How can double click to image which will have action to do something like
view detail or remove this image

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/KillerCodeMonkey/ngx-quill/issues/1246>, or unsubscribe

**Comment by tranhao167** [comment]
You have any example?, please!

**Comment by KillerCodeMonkey** [comment]
sadly no. :/

But just use some native javascript like 

```TS
quillContentElement
  .querySelectorAll('img')
  .addEventlister('click', (event) => {
    // do something like getting the src of the event target
  })
```
