### ISSUE TITLE
Function calls are not supported in decorators but 'QuillModule' was called.

### ISSUE THREAD

**Issue by Prasanth-FrontEnd** [KillerCodeMonkey/ngx-quill#1255]
I'm using Angular 9 version also I'have disabled the Ivy Compiler. I was using the "ngx-quill": "9.2.0" it was working fine in locally and dev environment.

I have successfully migrated the Angular version from 8 to 9 but only this error makes weird.

But in production it was throwing the weird error: 

`ERROR in Error during template compile of 'AppModule'
  Function calls are not supported in decorators but 'QuillModule' was called.
Unexpected value 'undefined' imported by the module 'AppModule'
Error during template compile of 'AppModule'
  Function calls are not supported in decorators but 'QuillModule' was called.
`

I have imported the module in App Module:

       QuillModule.forRoot({
            format: 'html'
        }),

In Html:

`<quill-view-html [content]="dynamicContent" theme="snow"></quill-view-html>`

**Comment by KillerCodeMonkey** [comment]
Could you Share your App Module configuration?

Sounds Like
https://github.com/KillerCodeMonkey/ngx-quill/issues/884

Did you added The quillmodule to The Imports Array?

Am 24.05.2021 in 17:47, Prasanth-FrontEnd ***@***.***>
schrieb:

I'm using Angular 9 version also I'have disabled the Ivy Compiler. I was
using the "ngx-quill": "9.2.0" it was working fine in locally and dev
environment.

I have successfully migrated the Angular version from 8 to 9 but only this
error makes weird.

But in production it was throwing the weird error:

ERROR in Error during template compile of 'AppModule' Function calls are
not supported in decorators but 'QuillModule' was called. Unexpected value
'undefined' imported by the module 'AppModule' Error during template
compile of 'AppModule' Function calls are not supported in decorators but
'QuillModule' was called.

I have imported the module in App Module:

   QuillModule.forRoot({
        format: 'html'
    }),

In Html:

<quill-view-html [content]="dynamicContent" theme="snow"></quill-view-html>

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/KillerCodeMonkey/ngx-quill/issues/1255>, or unsubscribe

**Comment by Prasanth-FrontEnd** [comment]
This is my App module configuration.

`@NgModule({
	imports: [
            QuillModule.forRoot({
                format: 'html'
            })
       ]`

**Comment by KillerCodeMonkey** [comment]
and is this your AppModule? or a child module?

You could try v9.1.1. or remove node_modules folder and reinstall node_modules. 
And keep in mind Angular 9 end of lifetime is 6th of august 2021 ;-). So i would just directly update to at least angular 10.

**Comment by Prasanth-FrontEnd** [comment]
this is my AppModule.

Will downgrade the version then update you.

Also, you are saying that Angular 9 version is supported for the application only upto  6th of august 2021(do you have official docs for this information). After that Angular 9 version is not supported for the application.

**Comment by KillerCodeMonkey** [comment]
https://angular.io/guide/releases just scroll a little bit down. there is a table with versions and support.

That is the reason i already removed it from the readme of ngx-quill here ;-)

**Comment by Prasanth-FrontEnd** [comment]
This is the error I'm getting after downgrading to the version - 9.1.1

ERROR in Error during template compile of 'DatamarketplaceAppModule'
  Function calls are not supported in decorators but 'QuillModule' was called.

Thanks for Angular release documentation.

**Comment by KillerCodeMonkey** [comment]
why did you disabled ivy renderer?

**Comment by KillerCodeMonkey** [comment]
seems like it depends on the angular version + tsconfig compiler settings: 
https://github.com/angular/angular/issues/23609#issuecomment-510871378

**Comment by Prasanth-FrontEnd** [comment]
While enabling the Ivy I was facing a lot of errors so for now I have disabled it. But I will do before August'2021.

**Comment by Prasanth-FrontEnd** [comment]
Yes it depends on tsconfig and Angular version.

I have tried all these combinations which is mentioned in the https://github.com/angular/angular/issues/23609

`"skipTemplateCodegen": true,
    "strictMetadataEmit": true,
    "fullTemplateTypeCheck": true


    "skipTemplateCodegen": false,
    "strictMetadataEmit": false


    "skipTemplateCodegen": false,
    "strictMetadataEmit": true,`

**Comment by Prasanth-FrontEnd** [comment]
Any update on this issue?

**Comment by KillerCodeMonkey** [comment]
do not know? what do you think? :D

**Comment by KillerCodeMonkey** [comment]
just try an older ngx-quill version. maybe some 8.x version. If that is not working for you. Just upgrade to angular 10.

i do not see that i can do anything for it. And in general i will not hotfix anything for angular 9, since there are 3 newer major versions available and LTS is dropped in august this year

**Comment by Prasanth-FrontEnd** [comment]
I have downgraded to the 8.0.0 but still it's throwing the same error. In that case, I will try to update Angular 10 then I will check and let you know.

**Comment by KillerCodeMonkey** [comment]
will close it for now. if angular 10 + the fitting ngx-quill version does not work for you, feel free to reopen it.

Hint: checkout ngx-quill-example repo. go through the commit history, because i had that example repo running for all the last ngx-quill and angular versions.

**Comment by Prasanth-FrontEnd** [comment]
Sure I will give update after the migration to Angular 10 version.
