### ISSUE TITLE
Show error message inside mat-form-field

### ISSUE THREAD

**Issue by begandroide** [KillerCodeMonkey/ngx-quill#1258]
Hi @KillerCodeMonkey thanks for the editor, is perfect.

I'm adding reactive form ngx-quill text-editor, because i need add validation errors and show messages, i built mat-quill with you reference [https://github.com/KillerCodeMonkey/ngx-quill-example/blob/master/src/app/mat-quill/mat-quill-base.ts](https://github.com/KillerCodeMonkey/ngx-quill-example/blob/master/src/app/mat-quill/mat-quill-base.ts), and works fine because correctly validate the control, but the error messages are not shown.

What part of the code is missing to show validation errors?

I hope use mat-quill like this:

```typescript
<mat-form-field>
 <mat-quill #matEditor name="editor" formControlName="controlName" [maxlength]="10" [required]="true"></mat-quill>
   <mat-error *ngIf="form.get('controlName').hasError('required')">
      {{ '::GenericForms:RequiredField' | Localization }}
    </mat-error>
    <mat-error *ngIf="form.get('controlName').hasError('maxlength')">
      {{ '::GenericForms:RequiredField' | Localization }}
    </mat-error>
    <mat-hint>{{Write here | Localization}}</mat-hint>
</mat-form-field>
```

Regards!

**Comment by KillerCodeMonkey** [comment]
i think i can not really help you with that. i have not that much experiences with material ui and i was not the original author of the mat quill example.

But i think you need to define or change the error state matcher:
https://stackoverflow.com/questions/46745171/angular-material-show-mat-error-on-button-click
https://material.angular.io/components/input/overview#custom-error-matcher

Since your question is not ngx-quill related i will close this issue
