### ISSUE TITLE
Two way data binding is not working for ngx-quill

### ISSUE THREAD

**Issue by kishor-syntel** [KillerCodeMonkey/ngx-quill#1279]
Two way data binding is not working for ngx-quill.

I am using 
Angular 10
ngx-quill 12

**Comment by KillerCodeMonkey** [comment]
And why so you think IT IS not working? Checkout Out My Demo examples.
There are examples with ngModel and formControl.

Just saying IT IS not working is lazy! Proof IT!
;-)




Am 18.06.2021 in 07:49, kishor-syntel ***@***.***> schrieb:

Two way data binding is not working for ngx-quill.

I am using
Angular 10
ngx-quill 12

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/KillerCodeMonkey/ngx-quill/issues/1279>, or unsubscribe
