### ISSUE TITLE
How to set path value when there is no system.config.js file for 'Unexpected token export' error

### ISSUE THREAD

**Issue by hegdevnayak** [KillerCodeMonkey/ngx-quill#128]
An angular project using angular-cli doesn't come with system.config.js. 
I'm using .net core with server-side rendering which throws 'Unexpected token export' error. 

The solution for 'Unexpected token export'is to set Path value to js files in system.config.js which I don't have. Please let me know the solution.

**Comment by KillerCodeMonkey** [comment]
i think this not a ngx-quill question.. more agular cli or ssr.

angular-cli without ssr is working out of the box. i tested it locally ... and you can add external script to your angular-cli.json - check the scripts section ;)

SSR is another topic. You need to mock Quill during ssr because quilljs is using the "document" object which is not available in ssr.

check out https://github.com/KillerCodeMonkey/ngx-quill/issues/91

**Comment by btots** [comment]
I have a similar issue trying to set up ngx-quill in my angular-cli.json. I apologize if this is a newbie question, but I'm struggling to figure out which files to include in the scripts section. Right now I've got:
 `  "../node_modules/quill/dist/quill.js",
     "../node_modules/ngx-quill/bundles/ngx-quill.umd.js"`
in, but I'm getting `quill.module.ts:13 Uncaught ReferenceError: require is not defined` in the console when using ng serve. What should be used?

**Comment by KillerCodeMonkey** [comment]
There is no need to add Both to the cli.json

Just install and use ngx-quill. The cli should bundle it out of the box.
