### ISSUE TITLE
Angular 12 - Webpack 5 Error

### ISSUE THREAD

**Issue by gorkemyontem** [KillerCodeMonkey/ngx-quill#1304]
Hi @KillerCodeMonkey I'm having problems with the Angular 12 update. I'm getting this error below. Which looks like a webpack 5 related issue.

![image](https://user-images.githubusercontent.com/8965495/125177957-e07eca00-e1e8-11eb-95a0-f31b1b0e9f5d.png)

My config is pretty basic, I'm **not** using a custom webpack config file. 
```
    "ngx-quill": "^14.1.2",
    "quill": "^1.3.7",
    "quill-image-compress": "^1.2.15",
    "quill-image-drop-module": "^1.0.3",
    "quill-image-resize-module": "^3.0.0",
    "quill-video-resize": "^1.0.0",
```

Do you know any workaround? Or any idea why would this happen?

**Comment by KillerCodeMonkey** [comment]
Yes this ist a webpack Error. Seems Like your config is not supporting svgs.

I would Check angular cli issues about that.


Am 11.07.2021 in 00:52, Görkem Yöntem ***@***.***> schrieb:

Hi @KillerCodeMonkey <https://github.com/KillerCodeMonkey> I'm having
problems with the Angular 12 update. I'm getting this error below. Which
looks like a webpack 5 related issue.

[image: image]
<https://user-images.githubusercontent.com/8965495/125177957-e07eca00-e1e8-11eb-95a0-f31b1b0e9f5d.png>

My config is pretty basic, I'm *not* using a custom webpack config file.

    "ngx-quill": "^14.1.2",
    "quill": "^1.3.7",
    "quill-image-compress": "^1.2.15",
    "quill-image-drop-module": "^1.0.3",
    "quill-image-resize-module": "^3.0.0",
    "quill-video-resize": "^1.0.0",

Do you know any workaround? Or any idea why would this happen?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/KillerCodeMonkey/ngx-quill/issues/1304>, or unsubscribe

**Comment by gorkemyontem** [comment]
Thank you for your answer @KillerCodeMonkey, I've created a clean Angular 12 project and it was working fine until I added plugins. Turns out,
```
import VideoResize from 'quill-video-resize';
Quill.register('modules/VideoResize', VideoResize);
```
lines were causing the problem. Of course, with a custom webpack configuration, this issue might get fixed, however, I confirm that this plugin doesn't work with a clean Angular 12 project.  
I will close this issue because it is not relevant to this repo. 

Thanks again!
