### ISSUE TITLE
ngModel doesn't update from API changes

### ISSUE THREAD

**Issue by AlanObject** [KillerCodeMonkey/ngx-quill#1346]
When I change the editor content with an `updateContents()` call, the `[(ngModel)]` doesn't change.

If the user changes something after the `updateContents()` call, the model is updated with the `updateContents()` and whatever the user changed.   

To demonstrate the problem, here is the template:

```html
<h1>Test Delta with ngx-quill</h1>

<quill-editor (onEditorCreated)="evtEditor($event)"
              name="editor" [(ngModel)]="content"></quill-editor>

<button type="button" (click)="clickDoDelta()">Do a Delta</button>

<h2>Content</h2>

{{ content }}
```

and the Component behind it:

```typescript
import { Component } from '@angular/core';
import Quill from 'quill';

// @ts-ignore
import Delta from 'quill-delta/lib/delta'

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss']
})
export class AppComponent {

  editor: Quill | null = null;

  content = '<h1>Test</h1><p>Hi There!</p>';

  constructor() {
  }

  clickDoDelta() {
    if (!this.editor) return;
    const delta = new Delta().retain(14).insert('\nGoodbye Then\n');
    this.editor.updateContents(delta);
    this.editor.update('api');  // does this do anything?
    console.log('Content is', this.content);
  }

  evtEditor(evt: Quill) {
    this.editor = evt;
    console.log('evtEditor', evt);
  }
}
```
After clicking the button, the `contents` instance variable does not change until the user types something in the editor window.  I thought maybe the `update()` call was what was needed, but it doesn't seem to do the trick.  Is there any way to get the editor Component to update the model?

**Comment by KillerCodeMonkey** [comment]
Check quilljs docs and ngx-quill readme carefully.

Quilljs allows as last Parameter for those update/set methods the source of
the change. Default is API and ngx-quill does not update controls and
models on API changes. Only on user changes.

So you have a predefined data flow per default:

- changing the model or control the angular way
- real change the content as user like typing in the editor.

You can activate updates for every source with a special input mentioned in
the readme.

But you should just pass the source "user" to quilljs API calls.

Keep in mind to maybe use angular reactive forms to work with
formControl.patchValue instead of the quill API

Alan ***@***.***> schrieb am Sa., 28. Aug. 2021, 19:11:

**Comment by AlanObject** [comment]
As hinted, after updating the code from:

```typescript
     this.editor.updateContents(delta);
```
to
```typescript
    this.editor.updateContents(delta, 'user');
```

the model now updates as expected.  In my opinion the the usage of the "source" parameter is not really very well documented.   Thanks for the help.
