### ISSUE TITLE
Violates the following Content Security Policy directive error

### ISSUE THREAD

**Issue by franconeilglovasa** [KillerCodeMonkey/ngx-quill#1417]
I'm having this error when I try to run it. Any idea how to fix this one? Thanks

```
Refused to apply inline style because it violates the following Content Security Policy directive: "style-src http://gc.kis.v2.scr.kaspersky-labs.com ws://gc.kis.v2.scr.kaspersky-labs.com". Either the 'unsafe-inline' keyword, a hash ('sha256-AkxMgySIKnm/Bm3wq/FtuHbcEKHo6Wvw1ScyTYCTQQA='), or a nonce ('nonce-...') is required to enable inline execution.

ns.AddDocumentStyles @ main.js?attr=7yafGeykWG82Dk_fSqBey1PFiaYaVJlfnscxAFGyWQXnaFgofmLx5zANlEm4kDZ4:409
```

**Comment by KillerCodeMonkey** [comment]
https://stackoverflow.com/questions/17766817/refused-to-apply-inline-style-because-it-violates-the-following-content-security#18428346

But in general: ngx-quill does not use inline styles and quilljs is using css classes for formatting.

I would rather check, if you are using inline styles somewhere

**Comment by KillerCodeMonkey** [comment]
Seems like quilljs is adding inline styles for colors
https://github.com/quilljs/quill/issues/1499
