### ISSUE TITLE
How to add a handler that references the editor itself?

### ISSUE THREAD

**Issue by Arthur-o-b** [KillerCodeMonkey/ngx-quill#1449]
I need a toolbar dropdown to insert some text snippets.
I got the dropdown mostly working, but when i click on the options, the handler doesn't seem to have the editor instance that it needs in order to insert the text.

```
quillConfig = {
    toolbar: {
      container: 
      [
        [{ 'insert': ['[Template]', '[Name]'] }],
        ['bold', 'italic', 'underline'],
        [{ header: 1 }, { header: 2 }],
        [{ list: 'ordered' }, { list: 'bullet' }],
      ],
      handlers: {
        'insert': function(value) {
          if (value) {
            console.log('handling: ' + value)
            this.editor.insertText(this.editor.getSelection().index, value)
          }
        }
      }
    } 
  };
```
  
with this i get

  **Uncaught TypeError: Cannot read properties of undefined (reading 'insertText')**

How can i use the editor in it's own handler?

**Comment by KillerCodeMonkey** [comment]
The problem is, that the quill handlers are executed outside of your
angular and class context.

Just try to use a fat arrow function for your handler. Or define the
function as classmember of the class and bind the current context:

handler () {...}

In the constructor

this.handler = this.handler.bind(this)

And then in your quill modules definition

insert: this.handler


Arthur-o-b ***@***.***> schrieb am Mo., 27. Dez. 2021, 16:23:

**Comment by Arthur-o-b** [comment]
This worked, but the issue itself was the way the team had implemented it before, they had the quillConfig completely out of scope.

Thanks.

**Comment by aarhusgregersen** [comment]
Just popping in for a question on a thread, as I believe this issue (or the solution at least) is similar to a problem I'm facing with the context of the `this` keyword.

Using the newest version of angular, however, I'm not able to use the syntax above for setting the `this.handleVideo = this.handleVideo.bind(this)` within the constructor, as the `this` keyword is disallowed there.

Is there another workaround I could go with?

Fundamentally my issue is that I'm unable to call other code in my TS component, because `this` gets reduced to the quill scope. Those were not the exact words used here, but I believe the problem was similar.

If I'm incorrect I'm happy to open another issue.
