### ISSUE TITLE
Not working with outlook addin project using angular 9

### ISSUE THREAD

**Issue by ajayiviewlab** [KillerCodeMonkey/ngx-quill#1451]
Hello

I have created office outlook add-ins for chat application. I used Angular 9. I have integrated rich texteditor(https://www.npmjs.com/package/ngx-quill)

My issues, I am unable to copy/paste the content into text editor (not all, but some of not from email)

![image](https://user-images.githubusercontent.com/96908433/147815369-c02f4633-7fb3-4260-9cd3-14c111e24251.png)

![image](https://user-images.githubusercontent.com/96908433/147815375-bb31626b-f475-447c-9c27-d75cac022bb5.png)

This is working fine if I used as angular application in website

BUT notworking in task pane of outlook

Thanks.

**Comment by KillerCodeMonkey** [comment]
First I do not support angular 9 anymore since it is not maintained by
angular.

Check the readme of supported versions.

Second I do not have any experiences with outlook addins.

The error looks like a native quilljs one.

Just debug what your selection index is. Before pasting.


ajayiviewlab ***@***.***> schrieb am Fr., 31. Dez. 2021,
10:32:

**Comment by ajayiviewlab** [comment]
Ok @KillerCodeMonkey 

Let me update my project cli, and test it again.

Just debug what your selection index is. Before pasting.
- you mean in native quilljs?

**Comment by KillerCodeMonkey** [comment]
ngx-quill is just an angular wrapper of quilljs https://github.com/quilljs/quill and the error you got is triggered by the quilljs instance

**Comment by KillerCodeMonkey** [comment]
i will close this because angular 9 is outdated and not maintained.

feel free to keep the issue up to date. :)
