### ISSUE TITLE
Quill loses formatting when loaded dynamically in ng-content block

### ISSUE THREAD

**Issue by KalenGibbons** [KillerCodeMonkey/ngx-quill#1500]
I created a CodeSandbox example that demonstrates the issue: https://codesandbox.io/s/funny-panna-8501u6?file=/src/app/app.component.html

When an ngx-quill instance is loaded into an ng-content block after initialization, all formatting on the content is removed.

**Comment by KillerCodeMonkey** [comment]
yep this is a known problem of quill, because even if you use ng-content the editor is rendered somewhere and this leads to that problem. if you are using mat-quill components you will run very often in that problem, because tabs, accordions or using content projections.

Workaround:
https://codesandbox.io/s/immutable-thunder-8etxf3

Only render the content when it should visible

**Comment by KalenGibbons** [comment]
@KillerCodeMonkey That makes sense, thanks for the workaround and the quick response.  It's appreciated.
