### ISSUE TITLE
Does ngModel work in v3.0.0?

### ISSUE THREAD

**Issue by dextersy** [KillerCodeMonkey/ngx-quill#1521]
I just wanted to make sure that v3.0.0 supports ngModel for the quill-editor.

I checked ngx-quill-example and it worked very well, but it's using 16.1.2.
In my project, I need to use v3.0.0 due to compatibility with Angular packages I'm using. When I bind quill-editor using ngModel, the value of the variable stays "undefined".

Hoping to get guidance on this, and thank you for this really great library!

**Comment by KillerCodeMonkey** [comment]
I really do not know what was working in v3^^.

Just check the commit or release history to find out.

I am only maintaining and supporting angular versions in the compatibility
table in the readme.

But I guess instead of a custom form control that old version has an input
like "content" and an output to grab the change or current value


Dexter Sy ***@***.***> schrieb am Do., 14. Apr. 2022, 08:31:

**Comment by mouhsineelachbi** [comment]
try to use name and id
`<quill-editor
(onContentChanged)="onBlur($event)"
(onBlur)="blur($event)"
[(ngModel)]="editorContent"
name="editorContent"
id="editorContent"
>
</quill-editor>`
