### ISSUE TITLE
(Question) get textContent of a Block

### ISSUE THREAD

**Issue by snakone** [KillerCodeMonkey/ngx-quill#1557]
Hello, i want to add an id to each H2

```ts
const Header = Quill.import('formats/header');

class CustomHeader extends Header {
  constructor(node: HTMLHeadingElement) {
    super(node);
    node.setAttribute('id', 'foo');
  }
}

Quill.register(CustomHeader, true);
```

this is working, but i need to add an ID i'd know, like the textContent from the **node**

example: `<h2>Getting started</h2>`  ----> `<h2 id="getting-started">Getting started</h2>`

thanks you so much!!!

**Comment by KillerCodeMonkey** [comment]
i think you can't just add the textcontent as an id, because there could be anything. even not unicode characters or chars you need to escape and so on.

And i guess your custom header constructor is called, when you add the h2-tag to the editor content and not the content itself.

i think what you want to do can not be achieved this easy.

you could check https://github.com/quilljs/quill/blob/develop/blots/block.js which methods are called, when you mark a text and format it as headline and so on. Maybe you can override an existing method like `insertAt` to grab the content. But keep in mind - you do not know if the content is safe to use ;-).

In general ask this at the quilljs repo. because i do not have that deep quilljs knowledge
