### ISSUE TITLE
Module '"quill"' has no exported member 'Delta'. Did you mean to use 'import Delta from "quill"' instead?

### ISSUE THREAD

**Issue by carepollo** [KillerCodeMonkey/ngx-quill#1587]
I did nothing special, install quill, ngx-quill and quill-image-reisize-module, then this error came up
![image](https://user-images.githubusercontent.com/67649525/182889250-2323c40a-9f6f-431e-8d38-400c6b112ea5.png)

I am using angular 14
It was solved just changing this line
![image](https://user-images.githubusercontent.com/67649525/182889809-cd9fa18d-a6e1-4626-9f2f-a9572a4a3559.png)
to this
![image](https://user-images.githubusercontent.com/67649525/182889883-e60de5ea-b38b-46a0-994c-5dc8a52afee0.png)
on the file mentioned in the error thrown
Is not throwing compiling errors anymore, but I am not sure if this would be a good solution when deploying or something.

**Comment by KillerCodeMonkey** [comment]
again and again... please install the correct quilljs (1.x) and typing (1.x) versions. and please use search through already closed issues first.

**Comment by inorganik** [comment]
@KillerCodeMonkey It would probably help if you mentioned somewhere about @types/quill package and which version to install.... currently all we have to go off of is error messages in our builds. And if you install the types package as it suggests, you get v2 which causes more errors.

For anyone coming across this issue with ngx-quill@17, do the following:
```
npm i -D @types/quill@1.3
```

**Comment by KillerCodeMonkey** [comment]
It's in the readme in the section about Installation... Soooo

**Comment by inorganik** [comment]
I see now, sorry

**Comment by inorganik** [comment]
@KillerCodeMonkey If you added the deps in projects/ngx-quill/package.json, you wouldn't even have to explain about which deps to install, they would get installed with the package

```json
"dependencies": {
    "quill": "^1.3.7",
    "@types/quill": "^1.3.10"
},
```

**Comment by KillerCodeMonkey** [comment]
And that's why they are peer dependencies. So when you are running npm I or yarn install - just do not ignore the warnings about missing oder unmet Peer dependencies ;-).

So you are open to choose which V1 version you wanna use and I am not limiting your project dependencies. That's how peer dependencies work and why they exist ;-)

**Comment by inorganik** [comment]
The @types package is not a peer dependency. 

Also, what is the use-case for choosing a different v1 I wonder. If you are using it for ngx-quill you'll want the specific version that's compatible with it. 

Finally if you use npm 8 and above, you have to pass a special flag to install anything without it blowing up if peer deps are incompatible. For these reasons, it seems like an easy choice to make them dependencies instead of peer dependencies
