### ISSUE TITLE
feature: Allow user edit html code

### ISSUE THREAD

**Issue by mostafacs** [KillerCodeMonkey/ngx-quill#162]
Can you allow user edit html code ? or Can I add custom button to the toolbar to add this feature ?

**Comment by KillerCodeMonkey** [comment]
Please Check Out the quilljs Repo. I Provide only an angular Wapper for
That. Thanks

Am 13.04.2018 4:23 nachm. schrieb "Mostafa" <notifications@github.com>:

Can you allow user edit html code ? or Can I add custom button to the
toolbar to add this feature ?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/KillerCodeMonkey/ngx-quill/issues/162>, or mute the
thread
