### ISSUE TITLE
Regarding table support in the quill editor with Angular 12 and ngx quill

### ISSUE THREAD

**Issue by sanjeeb-KL** [KillerCodeMonkey/ngx-quill#1625]
Hi , I am not getting how add table support in the ngx-quill editor ?
Angular version 12.2.15

**Comment by KillerCodeMonkey** [comment]
not that easy.

since there is only quilljs 1 final. v2 is just under development where table support will be added.

you could try to hacky use npms overrides to override ngx-quill quilljs peer dependencies to v2 dev version.

and if using typescript install @types/quill for v2.

And then fingers crossed it is working somehow :D
