### ISSUE TITLE
Custom toolbar select that inserts texts

### ISSUE THREAD

**Issue by jchapelle** [KillerCodeMonkey/ngx-quill#1638]
Is it possible with ngx-quill to create a custom toolbar dropdown or select that insert custom text or html in the editor ?

**Comment by KillerCodeMonkey** [comment]
sure, but the you have to define a toolbar-html-code by yourself. 

here a toolbar with custom fonts:
https://github.com/KillerCodeMonkey/ngx-quill-example/blob/master/src/app/custom-toolbar/custom-toolbar.component.html

but you could even add click listeners (native listeners!, because quill does not know anything from angular) to the dropdown items and so on. it is just javascript.

Or you can create a custom quill-module that handles it for you. Just checkout the code for the link or image module of quilljs
