### ISSUE TITLE
No new lines when inserting raw HTML

### ISSUE THREAD

**Issue by jasbyte** [KillerCodeMonkey/ngx-quill#1697]
When I insert this html:

```
<p>
<span><strong>%Description%</strong></span>
<span> (%Code%) was requested </span>
<span><strong>%Resource%</strong></span>
<span> </span>
<span><strong>Period </strong></span>
</p>
<p>
<span><strong>Duurtijd</strong></span>
<span>: %Duration%</span>
</p>
```

it converts it to:
```
<p>
<span><strong>%Description%</strong></span>
<span> (%Code%) was requested </span>
<span><strong>%Resource%</strong></span>
<span> </span>
<span><strong>Period </strong></span>
<span><strong>Duurtijd</strong></span>
<span>: %Duration%</span>
</p>

```
Which removes my new lines. If i then manualy add a new line it formats the HTML correctly. 

To do this I am using the writeValue function.

Is it something wrong i have been doing or is this a bug?

**Comment by KillerCodeMonkey** [comment]
its a quilljs issue. 

there is some magic happening when inserting.
And when i remember it correctly and "empty" or "new line" for quilljs is `<p></br></p>`.
So quill is combining both p-tags, because it is the same for quill.

And quilljs is not there to copy and paste wild other html, it is more like you are using quilljs with quilljs created content ;-).

Another thing is you can try to use divs instead of p-tags.
