### ISSUE TITLE
Authenticate image requests

### ISSUE THREAD

**Issue by lavaloop-official** [KillerCodeMonkey/ngx-quill#1729]
I successfully implemented that images are uploaded to the backend separately when using the quill.js editor. I want to be able to control who sees what images so I need to authenticate a user before he can view an image. I found [this guide](https://stackoverflow.com/questions/47811784/passing-authorization-header-for-images-src-to-remote-server-in-ionic-page) on StackOverflow on how to authenticate image requests from angular template. Can this also be applied to quil-view or do have to implement my own view for this feature? Thanks

**Comment by KillerCodeMonkey** [comment]
nope it can not, because quilljs does not know anything about angular and uses plain js + dom manipulation.

It depends a little bit the usage of quilljs.
Do you store html (not recommended) or the json object representation of the content.

so you could easy identifier images-urls and add a handling to download all images first and just embed the objecturl.

Or you could write your own image blot that does this for you when an image is rendered
