### ISSUE TITLE
Questions and Suggestions

### ISSUE THREAD

**Issue by skuzmin** [KillerCodeMonkey/ngx-quill#173]
Hi again,

I have 2 questions about editor and I would very grateful if you can help me with them :)

I wanted to add custom font sizes (10px, 12px and etc). I have done everything as in "read me" file, and of course it works like a charm. But I faced with two bad things:

**1)** I need to copy all default options to add change 1 option ( font size). So it would be great to add feature to change only 1 option or at least - possibility to get default options list ( then just change only 1 field and send back). Is it possible?

**2)** To change font size names, I need to write a lot of CSS ( because names are hardcoded in quill css)
Would be great if we could send options in "name-value" format, so name would set in CSS -> content.
Is it possible?

Thank you!

**Comment by KillerCodeMonkey** [comment]
Point 1: has some parts in common with: https://github.com/KillerCodeMonkey/ngx-quill/issues/171
Point 2: i will not change this handling, because i want to be create a "better" quilljs. :). It should be a small angular wrapper, without a lot of magic. Because this means more maintenance work.

If your first point is matches the global config issue, please close this issue. 

And feel free to contribute :)

**Comment by skuzmin** [comment]
Thx, it wasn't issue report, I just wanted to ask 2 question :)
