### ISSUE TITLE
TrimOnValidation and required options with empty lines

### ISSUE THREAD

**Issue by Steb95** [KillerCodeMonkey/ngx-quill#1788]
Hi, I'd like to ask a question about the `trimOnValidation` option.

If the option is set to `true` and the editor is also marked as `required`, simply adding one or more empty lines (e.g. pressing enter on the keyboard) makes the `requiredError` disappear in `formControl.errors`. Is that correct or is it my issue?

I suppose the issue is in [this line](https://github.com/KillerCodeMonkey/ngx-quill/blob/40102c35859b2baeefb18b0e1e4e7517d39c665e/projects/ngx-quill/src/lib/quill-editor.component.ts#L660C7-L660C7):
```
const onlyEmptyOperation = deltaOperations && deltaOperations.length === 1 && ['\n', ''].includes(deltaOperations[0].insert)
```
since when there are only empty lines `deltaOperations[0].insert` is `\n\n\n` (one `\n` for every line) and the condition
```
['\n', ''].includes(deltaOperations[0].insert)
```
is `false`, so [this condition](https://github.com/KillerCodeMonkey/ngx-quill/blob/40102c35859b2baeefb18b0e1e4e7517d39c665e/projects/ngx-quill/src/lib/quill-editor.component.ts#L680C1-L680C1)
```
if (this.required && !textLength && onlyEmptyOperation)
```
is also `false` and the error is not set.

Is this the desired behavior or an actual issue? I think that if the new lines aren't considered when checking the minLength and maxLength errors (i.e. when `trimOnValidation` is `true`), they shouldn't be considered when checking the required error either.

Thank you for your work!

**Comment by KillerCodeMonkey** [comment]
I am Just checking for the last New line, because it is known, That quill adds one per default. 

Just removing newlines would case other issues. 

So this behaviour is intended.
But I know it is Not perfect 


Am 13. Januar 2024 22:02:11 MEZ schrieb Steb95 ***@***.***>:

**Comment by Steb95** [comment]
I see... can't we check only the `textLength` (such as with `maxLength` and `minLegth`) without checking the `onlyEmptyOperation` condition when setting the required error?

(I accidetally closed the issue, sorry!)

**Comment by KillerCodeMonkey** [comment]
If I remember correctly my Initial idea was to not Mix Things up

So required means some User input is required. Even spaces or additional new lines.

Trim on validation is more or less there for min and max length to just trim spaces at the beginning and end, so additional spaces there are not counted.

Some may allow new lines as valid input and some not. So maybe combine required with minlength ?

**Comment by Steb95** [comment]
Yes, I suppose I can combine the two errors so that there is at least one non-blank character (or add myself the required error to the formControl if trimmed textLength is zero)... I just wanted to be sure that this was the intended behavior. Thank you!

**Comment by walberglez** [comment]
Hello and thank you for this repo.

I wanted to follow up on this issue because I think it's not possible to catch the empty text scenario even after combining required=true, minLength=1 and trimOnValidation=true. I consider as empty any combination of whitespaces and new lines.

For this to work, I think we would need to update line https://github.com/KillerCodeMonkey/ngx-quill/blob/fda2418021a06cbfa1d48ff5540b22ddc29408f3/projects/ngx-quill/src/lib/quill-editor.component.ts#L658

to:

`if (this.minLength && textLength < this.minLength) {`

When trimOnValidation is true and text is a combination of whitespace characters and new line characters, text length is 0. This makes this condition always false and the minLengthError is not detected.

Thank you.

**Comment by KillerCodeMonkey** [comment]
this is because i want to separate min-length and required.
so if you do not want to allow empty content - which is required the required error should shown.

So this is the reason i am only checking minlength if there is text content.

if a field is not required but has minLength of 1 it makes not much sense.
Just use required.

**Comment by walberglez** [comment]
I'm using required, minLength and trimOnValidation. I guess the purpose of trimOnValidation is a little bit confusing. I totally agree that required is needed to enforce there is at least one character typed, it doesn't matter what kind. Same for min length, it's used to enforce users type at least those many characters.

My confusion here is when we enable trimOnValidation to try to get rid of whitespace characters. For example, consider that a user typed one character `&nbsp` having required set to true, minLength set to 1 and trimOnValidation set to true. Required should pass. But minLength should not pass since text length should be 0 after trim is applied. Do you agree? This is not happening.

Please see this example: https://stackblitz.com/edit/3w3mgu?file=src%2Fapp%2Fapp.component.html
