### ISSUE TITLE
Question about using angular reactive forms on editor

### ISSUE THREAD

**Issue by haykoaghababyan** [KillerCodeMonkey/ngx-quill#1798]
Hi! 
I am using angular reactive formControl on editor but when I use
 control.setValue(someHtmlContent)   after that  I call editor.getText(); 
 values do not change , I don't want to use editor.clipboard.dangerouslyPasteHTML(0, linkedContent, 'api'); 
 
![image](https://github.com/KillerCodeMonkey/ngx-quill/assets/44507921/d700c0e9-c783-49b3-9def-02f2c61de418)

**Comment by KillerCodeMonkey** [comment]
maybe you are checking it to fast.

https://killercodemonkey.github.io/ngx-quill-example/

there is an example with "reactive" forms. you can trigger patch/setValue there and check the JS console. the Output `onContentChanged` is triggered afterwards with the changes. then the editor is up to date.

**Comment by KillerCodeMonkey** [comment]
Ah. in general the control changes are triggered as "api" or "silent".

Because ngx-quill only triggeres the outputs on real user changes. User is really typing or using the toolbar.
Because if you set the control value, you know that the value is changed to the value.

you have two options:

1. grab the editor instance from editorCreated output and listen to the "text-change" event of the native quill editor
2. set the property of the quill-editor-component of ngx-quill to get informed for all editor changes `trackChanges="all"`

**Comment by haykoaghababyan** [comment]
everything is clear, thank you

**Comment by KillerCodeMonkey** [comment]
feel free to close the issue if it is solved
