### ISSUE TITLE
preserveWhitespace  doesn't work with reactiveForms 

### ISSUE THREAD

**Issue by haykoaghababyan** [KillerCodeMonkey/ngx-quill#1812]
ngx-quill - "^25.0.1"
    quill - "2.0.0-rc.2"
    
    This is my test component template 
  ```
  <quill-editor
  [preserveWhitespace]="true"
  [formControl]="control">
</quill-editor>
```
    When I set the value   
    this.control.setValue(<p>Hayko           Aghababyan</p>);
    It shows without spaces 
<img width="442" alt="Screenshot 2024-03-06 at 14 59 31" src="https://github.com/KillerCodeMonkey/ngx-quill/assets/44507921/f8c97d8f-eb66-4670-9bff-fdf78f481670">

**Comment by KillerCodeMonkey** [comment]
does it work with ngModel?

**Comment by haykoaghababyan** [comment]
not 
I tried with ngModel but got the same result as with formControl

**Comment by KillerCodeMonkey** [comment]
can you check if this happens with ngx-quill 24 and quill v1, please?

**Comment by KillerCodeMonkey** [comment]
than maybe something in the quilljs styling changed. because i am just wrapping the editor element in a pre-tag if preserving is active.

**Comment by KillerCodeMonkey** [comment]
i tried a view things like hacky settings "white-space: pre-line" at the .ql-editor element but it is not working as well.

So i guess i need to find another solution or remove the option :S

**Comment by KillerCodeMonkey** [comment]
maybe quill itself is removing additional white spaces

**Comment by KillerCodeMonkey** [comment]
@luin do you know if quill v2 is removing duplicated whitespaces?

**Comment by luin** [comment]
`white-space` should do the trick actually. It's in quill.core.css in the bundle. Can you try if it works in [playground](https://quilljs.com/playground/snow#codeN4Ig9AlgdgJgpgDwHQAsAuBbANiAXCAHhggDcACCGAXgB0Q5i0B7AJzoD4CxiT2ap+BAM4BjFhAAOaMkJYja4aPGQArIRy6jxU9iAA0i2IiRq8IEUyhDpARwCuELFjJUyUOAHcyARQdOAFADkAMQMEMwsgXpkwPxkZBhMMHZYcEK4MXHxZMxMWABGAIYsGQDaWdlkpcBkKHCF8CVVAIzRAEzRAGaFWEJwALpkAL79ehXZpYH5eTBRZIHhPRAic4F2RixY0HCBo+PxkxAYhQDmO9GBFvAAtPlYTCIA1rtjUJV7b8Ov8RJYhSJwFAzOBNQIAYSYGAkTD6ZEKbzgEmWSBRUSyaDqGDgGUCQigTA8czAYDIrHm+Ts+TuO34QwAlABufj8eyOLBIPpoAAqiDQQQAgpUhZUAEKBRkgIZAA)?

**Comment by KillerCodeMonkey** [comment]
@luin but users can use html as source and then i use the clipboard module and this removes it

test:

```JS
quill.setContents(quill.clipboard.convert({ html: '<p>A     B</p>'}));
```

**Comment by luin** [comment]
Yeah but I think the behavior doesn't change compared to v1? We do collapse whitespace in clipboard unless the whitespaces are inside a `<pre>` tag. This makes sure users would see the exact whitespace size as they see in the source page.

**Comment by KillerCodeMonkey** [comment]
Strange but I am wrapping everything in a pre Tag. I changed Nothing there.

I was wrapping the Editor container in a pre Tag and thats it.

If you check my live demo the Preserve whitespace example is wrapped in a pre Tag, but White spaces are gone

Am 6. März 2024 15:55:59 MEZ schrieb Zihua Li ***@***.***>:

**Comment by luin** [comment]
By wrapping inside a `pre` tag, I mean the string passed to `clipboard.convert()`, instead of the editor container. There are two places that could cause whitespace collapsing:

1. `quill.clipboard.convert()` collapses whitespaces that are not inside `<pre>`. E.g. `quill.clipboard.convert({ html: '<p>A     B</p>'})` would be collapsed whereas `quill.clipboard.convert({ html: '<pre>A     B</pre>'})` won't.
2. The `white-space` style of the editor container. The default style sets the editor style to `white-space: pre-wrap` and I think in most cases it should not be changed to other values.

**Comment by KillerCodeMonkey** [comment]
But then there is a change how the clipboard worked in v1 and v2 right?

Since wrapping the Editor in a pre Tag was enough.

Am 6. März 2024 16:08:20 MEZ schrieb Zihua Li ***@***.***>:

**Comment by luin** [comment]
@KillerCodeMonkey Actually you are right. Turns out the behavior does change in v2. So in v1, clipboard inserted the HTML to a hidden `div` inside the editor container, and check whether we should collapse whitespaces or not with `getComputedStyles()`. That's why wrapping the editor with `<pre>` worked before. In v2, we parse the pasted HTML directly instead of inserting it to the DOM, so the previous way won't work.

The easiest way to preserve whitespace I think would be adding a [TEXT_NODE matcher](https://github.com/quilljs/quill/blob/df3549cfc5a51095230ad220236436d715ecd5a9/packages/quill/src/modules/clipboard.ts#L33) and overriding the behavior. Haven't tried it myself though.

**Comment by KillerCodeMonkey** [comment]
@luin thanks again for the response. so in general i will remove this functionality, because this would be to much of a change to the default quill behavior.

**Comment by KillerCodeMonkey** [comment]
feature removed with v25.1.0

**Comment by KillerCodeMonkey** [comment]
@luin sorry for bother you again, but with rc3 almost all my test cases are failing.

Do you changed something how to access the editor element?
https://github.com/KillerCodeMonkey/ngx-quill/actions/runs/8323103343/job/22772090567

**Comment by luin** [comment]
Oh I think it's a bug introduced in https://github.com/quilljs/quill/pull/4053, where we added back the `formats` option support. In the PR we merge the options with `{ ...quillDefaults, ...userProvidedOptions }`, so if you pass `{ registry: undefined }` when creating Quill instances, the registry will become `undefined`, whereas the expected behavior is that undefined values should be ignored.

Thanks for pinging me. Will create a fix soon!

**Comment by KillerCodeMonkey** [comment]
i have to thank for the fast response (i am searching problems first on my side... so it is nice to get fast feedback)

**Comment by luin** [comment]
Can you try `quill@0.0.0-experimental-bbb69eede-20240320`? It's rc3 with this config fix. I ran the test against it and there's one failing test related to `formats`. I think it makes sense as we brought `formats` back.
