### ISSUE TITLE
NPMJS advertises v23.0.3 as latest release, GitHub shows v26.0.2

### ISSUE THREAD

**Issue by KeithGillette** [KillerCodeMonkey/ngx-quill#1875]
`npm install ngx-quill@latest` pulls `ngx-quill@23.0.3`

**Comment by KillerCodeMonkey** [comment]
It is just because I forget that crappy system of npmjs... if you release a new Version of an oder major Version you need to use, `npm publish --tag old-version`... I just missed the Tag -.- ....sadly this is even needed for publishing packages.



Am 17. Juni 2024 20:39:36 MESZ schrieb Keith Gillette ***@***.***>:

**Comment by KillerCodeMonkey** [comment]
should be fixed now.
