### ISSUE TITLE
On blur event

### ISSUE THREAD

**Issue by Earthii** [KillerCodeMonkey/ngx-quill#189]
Currently, ngx-quill supports three output events. However, as an editor, it would be valuable to have the on blur event. I am aware that QuillJs does not support this yet. 
This can be followed here -> https://github.com/quilljs/quill/issues/1951

However, because  quill editor is wrapped in angular, i thought it might be possible to add a blur event.

**Comment by Earthii** [comment]
As explained in the quills issue, just to add the knowledge here:

My test case was that the editor should fire a blur event when you click away from the editor.
However, even we have typed some words, and then proceed to clicking the bold button in the toolbar, no events are fired. Not even the onSelectionChanged

**Comment by KillerCodeMonkey** [comment]
yeah this is correct, because if you click a button in the toolbar is not a "blur"-case, because you are not loosing focus or change the selection. Even through quilljs works with a content-editable div, it creates on its own. Everything i would implement as "blur" would be not 100% correct.

**Comment by MNorgren** [comment]
There is a good use case for a blur event that cannot be solved by using the onSelectionChanged.

i.e. - When a user is creating a new record of some sort, all of my input fields are considered untouched and therefore do not display any error message. The error message only displays when the user has either touched or changed the value of a FormControl.

If the user Tabs through the fields and leaves them unchanged, the FormControl should be marked Touched as the user has entered that formControl. 

How about a (editorBlurred) instead of (blur) to distinguish that it was not a button press?
