### ISSUE TITLE
Zonejs

### ISSUE THREAD

**Issue by prido1** [KillerCodeMonkey/ngx-quill#1890]
Will this work on zoneless environment

**Comment by KillerCodeMonkey** [comment]
@Angelinsky7 if like to contribute... there are a bunch of tests to "readd" and adapt :) for the quill-editor-component

https://github.com/KillerCodeMonkey/ngx-quill/pull/2007

**Comment by Angelinsky7** [comment]
@KillerCodeMonkey hello, thanks for you answer. i cannot promise anything but if i've got some time i'll gladly help you make this lib zoneless

:-D

**Comment by KillerCodeMonkey** [comment]
I started already to remove zonejs from the lib.

Refactored the code to use input-signal observables to subscribe for changes and using afterNextRender instead of ngOnChanges and ngAfterViewInit hooks.

Seems like it is working - unit tests are green for the view-components after refactoring them, too.

Only the quill-editor-component needs to be refactored and fixed.
