### ISSUE TITLE
Height in given percentage / full screen editor

### ISSUE THREAD

**Issue by jowin202** [KillerCodeMonkey/ngx-quill#1906]
Hello,

I'm currently using the editor like this:
```
<quill-editor [(ngModel)]="htmlText"
  placeholder="Enter Text"
  [modules]="quillConfig"
  [styles]="{minHeight: '250px', maxHeight: '500px', overflow: 'auto'}"></quill-editor>
```

The sizes are adjustable as long as I give the size in pixels. However, if I want the editor to fill the whole page (depending on screen size), it does not work. I can't enter something like height: '90%', this values will be ignored. Is there any minimal example, where the editor takes ~90% of screen height?

kind regards

**Comment by KillerCodeMonkey** [comment]
percentage is not working since the parents do not have a real height i guess. using "vh" should work out of the box. In any other cases you need to make sure that the parent nodes have a height.

![Bildschirmfoto_20240730_081133](https://github.com/user-attachments/assets/d19be6a5-8dab-4e41-b0e1-06f29b1b585e)

**Comment by jowin202** [comment]
thank you, this has solved everything :)
