### ISSUE TITLE
Media not loading in Ionic/Android

### ISSUE THREAD

**Issue by Saqib92** [KillerCodeMonkey/ngx-quill#1945]
When i am trying to add Media (images or videos) it is working for Web but not working for Android app. i am using latest IONIC + Capacitor + Android 14.

**Comment by KillerCodeMonkey** [comment]
i have no special handling about adding media to it .

But keep in mind in angular you need do sanitize content/urls and so on and quill only supports base64 images per default.

Your description is a little bit short. maybe add some more information (quill, ngx-quill,angular, ionic versions..). possible error messages in the js console, code, reproduction examples...

Because it could be many things even failures in your implementation.

And check quilljs repo for issues:
https://github.com/slab/quill/issues/3588

Thanks

**Comment by Saqib92** [comment]
Details are:

```
"quill": "^2.0.2",
"ngx-quill": "^25.3.3",
"@ionic/angular": "^7.5.0",
"@angular/core": "^18.2.0"
```


.html:
```
<quill-editor [styles]="{height: '350px'}" (onFocus)="focus($event)" (onNativeFocus)="nativeFocus($event)"
        (onEditorChanged)="changedEditor($event)" (onBlur)="blur($event)" (onNativeBlur)="nativeBlur($event)"
        (onEditorCreated)="created($event)"></quill-editor>
```

.ts:


```

import { EditorChangeContent, EditorChangeSelection, QuillEditorComponent } from 'ngx-quill';
import Quill from 'quill';


created(event: Quill | any) {
    // tslint:disable-next-line:no-console
    console.log('editor-created', event)
  }

  changedEditor(event: EditorChangeContent | EditorChangeSelection | any) {
    // tslint:disable-next-line:no-console
    console.log('editor-change', event);
  }

  focus($event: any) {
    // tslint:disable-next-line:no-console
    console.log('focus', $event)

  }

  nativeFocus($event: any) {
    // tslint:disable-next-line:no-console
    console.log('native-focus', $event)
  }

  blur($event: any) {
    // tslint:disable-next-line:no-console
    console.log('blur', $event)

  }

  nativeBlur($event: any) {
    // tslint:disable-next-line:no-console
    console.log('native-blur', $event)
  }
```

**Comment by KillerCodeMonkey** [comment]
okay then i guess you need to checkout the quilljs issue i linked and ask to reopen it.
It is not an ngx-quill issue.

**Comment by Saqib92** [comment]
Thank you.
