### ISSUE TITLE
Image resize not working

### ISSUE THREAD

**Issue by lakinmohapatra** [KillerCodeMonkey/ngx-quill#221]
Unable to resize image and insert image url . 
Also need an option to insert html into it.

**Comment by KillerCodeMonkey** [comment]
there for you have to add a quill addon, check out the demo repo...

if you want additional features in quilljs, ask in the quilljs repo or add your own add.

this is only an angular wrapper for quilljs

**Comment by lakinmohapatra** [comment]
Hey , need one help from you. 
After embedding image into quill, cursor always stays at top. Its not moving. 
How can i prevent it. Please let me know. 
 this.editor.insertEmbed(this.delta, 'image', 'http://localhost:8080' + response);

**Comment by darshanDevrai** [comment]
@lakinmohapatra 

> After embedding image into quill, cursor always stays at top. Its not moving.

I am having the same issue.
Have you found solution to this problem yet?

**Comment by KillerCodeMonkey** [comment]
just provide a demo repo or a plunkr or stackblitz to reproduce this?

**Comment by darshanDevrai** [comment]
@KillerCodeMonkey ,
I was facing this issue while inserting raw html string of img tag with width and height attribute. 
This problem is solved when I used delta insertEmbed() and set the width and height in style.css like -
~~~
.ql-editor img , iframe{
   width: 600px;
   min-height:450px;
   height: auto;
   display: block;
   margin: 0 auto; // center the image
 }
~~~ 
I think this is a more elegant way than using html strings. Am I right?
BTW, Thank you for this great wrapper :)

**Comment by KillerCodeMonkey** [comment]
instead of style all img and iframes yoiu could simply pass width and height as attributes;
https://quilljs.com/docs/delta/#embeds

So you only set it for the uploaded images.

I do not tested it, but thats what i would try :)

**Comment by darshanDevrai** [comment]
@KillerCodeMonkey ,
As per your suggestion I got this working 
~~~
let selection = this.quillInstance.getSelection();
this.quillInstance.updateContents(
  {
       retain: selection.index+1 
  },
  {
    insert: {
      image: 'https://material.angular.io/assets/img/examples/shiba2.jpg'
    },
    attributes: {
      width:700,
      height:400,
      alt:'alternate text',
    }
  },

)
~~~

Thank you for your help :) 👍
