### ISSUE TITLE
Setting Initial Value

### ISSUE THREAD

**Issue by joshrathke** [KillerCodeMonkey/ngx-quill#226]
I have scoured the documentation for this along with previous issues and can't find anyway to set the initial value of the editor. Neither ngModel or formControl inputs appear to be available to the `quill-editor`. Can someone shed some light on the best way to do this?

I have tried both [formControl] and [ngModel], both of which throw 'isn't a known property of 'quill editor'' error. Any ideas?

**Comment by joshrathke** [comment]
I realized that in wrapping the quill editor in its own child module I needed to import the Reactive Forms Module.

**Comment by KillerCodeMonkey** [comment]
Do You have a Demo Repo? Checkout the ngx-quill-example Repo linked in the
readme.

There You See an example with ngModel and formControl

Luiz Daniel Lima <notifications@github.com> schrieb am Do., 27. Sep. 2018,
15:24:

**Comment by luizdanielmlima** [comment]
Hi, thank for answering so quickly. First of all, thank you for the ngx-quill project, its much appreciated by the community. I´ve been using Angular for the past 4 months, so I don´t have much experience with it ;-)

I tried to use ngx-quill since yesterday morning and as I said and can´t make the "binding" work so I can set and get its value (the html content). Here is what I did:

1) I installed the packages as instructed in the github page, here is my package.json dependencies:

`"dependencies": {
    "@angular/animations": "^6.0.0",
    "@angular/cdk": "^7.0.0-beta.0",
    "@angular/common": "^6.0.0",
    "@angular/compiler": "^6.0.0",
    "@angular/core": "^6.0.0",
    "@angular/forms": "^6.0.0",
    "@angular/http": "^6.0.0",
    "@angular/platform-browser": "^6.0.0",
    "@angular/platform-browser-dynamic": "^6.0.0",
    "@angular/router": "^6.0.0",
    "@ng-bootstrap/ng-bootstrap": "^3.2.0",
    "@types/quill": "^1.3.10",
    "angular2-flash-messages": "^3.0.1",
    "angularfire2": "^5.0.0-rc.12",
    "bootstrap": "^4.1.3",
    "core-js": "^2.5.4",
    "firebase": "^5.4.2",
    "jquery": "^3.3.1",
    "ngx-quill": "^3.6.0",
    "popper.js": "^1.14.4",
    "quill": "^1.3.6",
    "rxjs": "^6.3.3",
    "zone.js": "^0.8.26"
  },`

2) Then I set the needed Modules in my app.module.ts, including the FormsModule and ReactiveFormsModule (so I coult try both approaches)

`import { FormsModule, ReactiveFormsModule } from "@angular/Forms";
import { QuillModule } from "ngx-quill";

(...)

  imports: [
    BrowserModule,
    AppRoutingModule,
    FormsModule,
    ReactiveFormsModule,
    (...)
    QuillModule
  ],
`

3) In my component, I imported the "QuillEditorComponent", I managed to show the editor and even customize the toolbar, I can type it, etc.

4) But I ran into some erros when I tried to use the [(ngModel)]="editorContent" in the quill-editor html tag. I had to use ngDefaultControl, after that, no erros. But I still couldn't get/set the value of the editor. The (onContentChanged) works (when I type and can log the html content and see the content), but I need to set the initial value of the editor (an html content that I get from Firestore) so...

`<quill-editor ngDefaultControl #editor [(ngModel)]="editorContent" [placeholder]="placeholder" [modules]="editorModules"
          [style]="{height: '200px'}" (onEditorCreated)="setFocus($event)" (onContentChanged)="saveTextEditorContent($event)"></quill-editor>`

5) Then I tried to use Reactive Forms, but still no progress:

`        <form [formGroup]="formWithQuill">
          <quill-editor formControlName="richEditor" [placeholder]="placeholder" [modules]="editorModules" [style]="{height: '200px'}"
            ngDefaultControl></quill-editor>
          <input type="text" formControlName="textInput">
        </form>`

6) To be honest, I´m kind of overwhelmed by your example, since it contains a lot of "use cases" and then the code is huge. I think it would be interesting to separate them or even put some very simple examples of setting ngx-quill up in a simlple project, specially a simple html, with ng-Model and getting the html of the editor.

**I´m sorry for all the text, thanks for your patience, any help is appreciated!**

**Comment by KillerCodeMonkey** [comment]
What happens when You Set the editorContent variable to a fixed string
instead of a value laden from the firestore?

Luiz Daniel Lima <notifications@github.com> schrieb am Do., 27. Sep. 2018,
16:03:

**Comment by luizdanielmlima** [comment]
Yes, I´ve tried that, just setting it like:  
`editorContent = "BLA";`

I have the feeling that I missed something in the set-up (?). I even put the css paths in my angular.json, but I was in doubt if I should put anything in the "scripts" path too ....

Using a Reactive Form, I tried to set it, on the .ts file, on the ngOnInit() method, like this: 

`    this.formWithQuill = new FormGroup({
      richEditor: new FormControl("bla"),
    });`

and in the HTML:

` <form [formGroup]="formWithQuill">
          <quill-editor formControlName="richEditor" [placeholder]="placeholder" [modules]="editorModules" [style]="{height: '200px'}"
            ngDefaultControl></quill-editor>
</form>`

I just tried an update, running "npm update", but.. nothing. What I do get a strange error when I use "ng serve", but I´m not sure if it´s related:

`WARNING in ./node_modules/@angular/Forms/fesm5/forms.js
There are multiple modules with names that only differ in casing.
This can lead to unexpected behavior when compiling on a filesystem with other case-semantic.
Use equal casing. Compare these module identifiers:
* C:\WebDev\Angular\vizimob-editor3\node_modules\@angular\Forms\fesm5\forms.js
    Used by 3 module(s), i. e.
    C:\WebDev\Angular\vizimob-editor3\node_modules\@ngtools\webpack\src\index.js!C:\WebDev\Angular\vizimob-editor3\src\app\app.module.ts
* C:\WebDev\Angular\vizimob-editor3\node_modules\@angular\forms\fesm5\forms.js
    Used by 17 module(s), i. e.
    C:\WebDev\Angular\vizimob-editor3\node_modules\@ngtools\webpack\src\index.js!C:\WebDev\Angular\vizimob-editor3\src\app\components\telas\tela-implant\tela-implant.component.ts`

**Comment by KillerCodeMonkey** [comment]
And If You Use the control and the component without wrapping it in a
<Form> Tag?

Never tried it thou... Maybe There happens something strange.

Luiz Daniel Lima <notifications@github.com> schrieb am Do., 27. Sep. 2018,
16:29:

**Comment by KillerCodeMonkey** [comment]
Maybe You Can checkout my ngx-quill-angular-cli Repo add a Form an
formcontrol to Check that minimal example

Bengt Weiße <bengtler@googlemail.com> schrieb am Do., 27. Sep. 2018, 16:31:

**Comment by luizdanielmlima** [comment]
ok, I will try that. Just a "newbie" question: after I download the files from the Repo, what is the best way to "rebuild" the node_modules folder? Do I have to manually check the packages on the packages.json file and then run every npm install ... that it´s needed?

**Comment by KillerCodeMonkey** [comment]
Ehhhh You download the Folder, Extract the Files. Open a Terminal/Shell,
Navigation to the Folder.

Then Run npm install.

If that finished Use ng serve or npm Start.

Luiz Daniel Lima <notifications@github.com> schrieb am Do., 27. Sep. 2018,
16:39:

**Comment by luizdanielmlima** [comment]
Thank you, I downloaded the files, then npm install and after that ng serve. But I got this error:

Local workspace file ('angular.json') could not be found.
Error: Local workspace file ('angular.json') could not be found.
    at WorkspaceLoader._getProjectWorkspaceFilePath (C:\WebDev\Angular\ngx-quill-angular-cli-master\node_modules\@angular\cli\models\workspace-loader.js:44:19)
    at WorkspaceLoader.loadWorkspace (C:\WebDev\Angular\ngx-quill-angular-cli-master\node_modules\@angular\cli\models\workspace-loader.js:31:21)
    at ServeCommand._loadWorkspaceAndArchitect (C:\WebDev\Angular\ngx-quill-angular-cli-master\node_modules\@angular\cli\models\architect-command.js:201:32)
    at ServeCommand.<anonymous> (C:\WebDev\Angular\ngx-quill-angular-cli-master\node_modules\@angular\cli\models\architect-command.js:53:25)
    at Generator.next (<anonymous>)
    at C:\WebDev\Angular\ngx-quill-angular-cli-master\node_modules\@angular\cli\models\architect-command.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (C:\WebDev\Angular\ngx-quill-angular-cli-master\node_modules\@angular\cli\models\architect-command.js:3:12)
    at ServeCommand.initialize (C:\WebDev\Angular\ngx-quill-angular-cli-master\node_modules\@angular\cli\models\architect-command.js:52:16)
    at Object.<anonymous> (C:\WebDev\Angular\ngx-quill-angular-cli-master\node_modules\@angular\cli\models\command-runner.js:127:23)

**Comment by luizdanielmlima** [comment]
hi, I managed to "borrow" a angular.json file from another project, changed the project name in a couple of places. I also included a styles.css file (blank) and declared the 3 .css files needed in the angular.json file, in the "styles" section:

            "styles": [
              "src/styles.css",
              "node_modules/quill/dist/quill.core.css",
              "node_modules/quill/dist/quill.bubble.css",
              "node_modules/quill/dist/quill.snow.css"
            ],

It´s running!  I will try now to test the [(ngModel)] .... Thank you

**Comment by KillerCodeMonkey** [comment]
Nice. Strange i need to Check why the angular.json is missing

Luiz Daniel Lima <notifications@github.com> schrieb am Do., 27. Sep. 2018,
19:58:

**Comment by KillerCodeMonkey** [comment]
Or did You downloaded the ngx-quill-example Repo?

There is anotherone for angular-cli under my Repo List.

Sry. I am only on my mobile :)

Bengt Weiße <bengtler@googlemail.com> schrieb am Do., 27. Sep. 2018, 20:06:

**Comment by luizdanielmlima** [comment]
huum... I´m back to where it all begins... when I try using ngModel, I get this error:

Uncaught Error: Template parse errors:
Can't bind to 'ngModel' since it isn't a known property of 'quill-editor'.
1. If 'quill-editor' is an Angular component and it has 'ngModel' input, then verify that it is part of this module.
2. If 'quill-editor' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("uill-editor [style]="{height: '200px'}"></quill-editor> -->

<quill-editor ngDefaultControl #editor [ERROR ->][(ngModel)]="editorContent" [style]="{height: '200px'}"></quill-editor>"): ng:///AppModule/AppComponent.html@11:39
    at syntaxError (compiler.js:1021)
    at TemplateParser.push../node_modules/@angular/compiler/fesm5/compiler.js.TemplateParser.parse (compiler.js:14830)
    at JitCompiler.push../node_modules/@angular/compiler/fesm5/compiler.js.JitCompiler._parseTemplate (compiler.js:24018)
    at JitCompiler.push../node_modules/@angular/compiler/fesm5/compiler.js.JitCompiler._compileTemplate (compiler.js:24005)
    at compiler.js:23948
    at Set.forEach (<anonymous>)
    at JitCompiler.push../node_modules/@angular/compiler/fesm5/compiler.js.JitCompiler._compileComponents (compiler.js:23948)
    at compiler.js:23858
    at Object.then (compiler.js:1012)
    at JitCompiler.push../node_modules/@angular/compiler/fesm5/compiler.js.JitCompiler._compileModuleAndComponents (compiler.js:23857)

**Comment by luizdanielmlima** [comment]
is there a way to set/get the content in the quill editor via programming? Link if I create a Quill instance programatically and use a pre-built method, like setContent or getContent ...?

**Comment by luizdanielmlima** [comment]
oops, I noticed in app.module.ts the FormsModule wasn´t there so I imported. I still get an erro though, although different this time...

HTML:

<div style="text-align:center">
  <h1>
    Welcome to {{ title }}!
  </h1>

  <quill-editor [(ngModel)]="editorContent" [style]="{height: '200px'}"></quill-editor>
</div>

TS:

import { Component } from "@angular/core";

import { QuillEditorComponent } from "ngx-quill";

// import * as Quill from "quill";
// console.log(Quill);

@Component({
  selector: "app-root",
  templateUrl: "./app.component.html",
  styleUrls: ["./app.component.scss"]
})
export class AppComponent {
  title = "app";
  editorContent = "<h1> Please Work Quill!</h1>";

  constructor() {
    this.editorContent = "<h2> And now?!</h2>";
  }
}

ERROR:

AppComponent.html:7 ERROR Error: No value accessor for form control with unspecified name attribute
    at _throwError (forms.js:1732)
    at setUpControl (forms.js:1642)
    at NgModel.push../node_modules/@angular/Forms/fesm5/forms.js.NgModel._setUpStandalone (forms.js:4088)
    at NgModel.push../node_modules/@angular/Forms/fesm5/forms.js.NgModel._setUpControl (forms.js:4075)
    at NgModel.push../node_modules/@angular/Forms/fesm5/forms.js.NgModel.ngOnChanges (forms.js:4035)
    at checkAndUpdateDirectiveInline (core.js:9246)
    at checkAndUpdateNodeInline (core.js:10514)
    at checkAndUpdateNode (core.js:10476)
    at debugCheckAndUpdateNode (core.js:11109)
    at debugCheckDirectivesFn (core.js:11069)

**Comment by luizdanielmlima** [comment]
(sorry, for the html "lost" in there)

**Comment by KillerCodeMonkey** [comment]
You could Use plain quilljs. But in Your case You need to add FormsModule
to the app
>
> Module Imports.

**Comment by KillerCodeMonkey** [comment]
Remove the default control please this should Not be necessary.

Luiz Daniel Lima <notifications@github.com> schrieb am Do., 27. Sep. 2018,
20:26:

**Comment by KillerCodeMonkey** [comment]
Because this is only available If You are using reactiveforms with
formControl

Bengt Weiße <bengtler@googlemail.com> schrieb am Do., 27. Sep. 2018, 20:27:

**Comment by luizdanielmlima** [comment]
Hello Bengt, I made a mistake before (I sent you the HTML code with the ngDefaultControl), in fact, when remove the ngDefaultControl, THEN I get the error that I sent you. 

When I put back the ngDefaultControl, the error is gone, but i STILL can´t make the ngModel work. I wonder if it has anything to do with the lifecycle or... well I don´t know what else I can do anymore :-(

**Comment by luizdanielmlima** [comment]
I noticed something interesting, by adding a field in the HTML with the double {{ }} . Although the editor doesn´t show the "editorContent" whe the page loads, the binding seems to exist, since whe I type something in the editor it disappears in the space above the editor (the showContent area).

In the other project I noticed, logging the onContentChange event,, that it turns the editorContent into undefined.... go figures...

new HTML:

```<div style="text-align:center">
  <h1>
    Welcome to {{ title }}!
  </h1>
  <br>

  <h4>
    The content in the quill editor is: <span>{{ editorContent }}</span>
  </h4>
  <p id="showContent">
    {{ editorContent }}
  </p>
  <br>

  <quill-editor [(ngModel)]="editorContent" [style]="{height: '200px'}" ngDefaultControl></quill-editor>
</div>```

**Comment by KillerCodeMonkey** [comment]
Dude i Do Not Know what you are doin ^^... My example repo works with
ngModel and formControl...  Without adding special Attributes. Could You
Provide me an Repo with Your Code?

Luiz Daniel Lima <notifications@github.com> schrieb am Do., 27. Sep. 2018,
20:49:

**Comment by luizdanielmlima** [comment]
I will try, never done before... will take a look how its done and I let you know when it´s there

**Comment by luizdanielmlima** [comment]
Hi Bengt, 

 After researching several discussions on github and others, I came across this discussion (https://www.bountysource.com/issues/37318190-no-value-accessor-for-form-control) where it shows that this kind of inconsistency can be related to the path of the forms module.

Well, just to give it a try, I changed my form import declarations in the app.module.ts from:

```import { FormsModule, ReactiveFormsModule } from "@angular/Forms";```

to

```import { FormsModule, ReactiveFormsModule } from "@angular/forms";```

Yes, just /Forms to /forms ... and... the binding is working now! Incredible, 1 day of work just because of this. How on earth would I now that? This imports are automatically done by VS Code so...

Well. I think I can get back to work now.

Anyway, I appreciate your help very much!!
THANK YOU

**Comment by KillerCodeMonkey** [comment]
Maybe this was the hint in the warning You got earlier ;) Glad You got it

Luiz Daniel Lima <notifications@github.com> schrieb am Do., 27. Sep. 2018,
22:11:

**Comment by kumarmageshr** [comment]
Is there workaround for the above issue?

**Comment by KillerCodeMonkey** [comment]
Add FormsModule for ngModel or ReactiveFormsModule to your Imports Port of
your ngModel


This hast nothing to so with ngxquill. IT IS Basic angular knowledge...

Am Fr., 25. Jan. 2019, 03:16 hat Mahesh Kumar Raju <notifications@github.com>
geschrieben:

**Comment by Maddy2894** [comment]
Hi Bengt,

First of all thank you for this project, i could implement it using <quill-editor></quill-editor> in my HTML file and save the content too in the database. But the problem is it is saved with HTML tags and when i retrieve it in another page, it displays with html tags. How to overcome html tags, save and retrieve without html tags. I looked all over google, stackoverflow, soultions are either for angularJS or not answered. I am currently using angular 7.

Cheers

**Comment by Maddy2894** [comment]
Is this what you meant?
Outputs
onEditorCreated - editor instance
editor
onContentChanged - text is updated
{
  editor: editorInstance,
  html: html,
  text: text,
  content: content,
  delta: delta,
  oldDelta: oldDelta,
  source: source
}
onSelectionChanged - selection is updated
{
  editor: editorInstance,
  range: range,
  oldRange: oldRange,
  source: source
}

**Comment by KillerCodeMonkey** [comment]
nope:
https://github.com/KillerCodeMonkey/ngx-quill#config

and then the 

```
format - model format - default: html, values: html | object | text | json, sets the model value type - html = html string, object = quill operation object, json = quill operation json, text = plain text
```

https://github.com/KillerCodeMonkey/ngx-quill-example/tree/master/src/app/format-object
or 
https://github.com/KillerCodeMonkey/ngx-quill-example/tree/master/src/app/format-json

And as live example:
https://killercodemonkey.github.io/ngx-quill-example/

the Format - JSON and Format object example.

The outputs are only wrappers of the quilljs events ;). And should be only used for advanced usages.

**Comment by Maddy2894** [comment]
Thank you for the quick response and solution. format="text" solved it for me.

Cheers

**Comment by Maddy2894** [comment]
One last doubt, eventhough it retrieves only text from database, it is adding /n by default at the end. When enter key is pressed before submiting, it stores as /n/n. Reference: image
<img width="505" alt="screen shot 2019-01-27 at 9 48 17 pm" src="https://user-images.githubusercontent.com/42700140/51800025-8dfdfd00-227d-11e9-9bdb-a0f09c453935.png">

**Comment by KillerCodeMonkey** [comment]
Yeah because /n IS the Text newline representation ;).

Just remove it before sending IT to your Backend. This IS the default
quilljs behavior and i will Not Change IT.

Am So., 27. Jan. 2019, 11:50 hat Madhavan Sundararaj <
notifications@github.com> geschrieben:

**Comment by KillerCodeMonkey** [comment]
And a question why using a wysiwyg Editor when simply storing plain Text?

Just use a textarea

Am So., 27. Jan. 2019, 11:57 hat Bengt Weiße <bengtler@googlemail.com>
geschrieben:

**Comment by Maddy2894** [comment]
You are right, but while retrieving, it does not retrieve with a new line. Please see below images for reference. And yea, I could use text area, but toolbar options of WYSIWYG Editor is a requirement.

<img width="545" alt="screen shot 2019-01-27 at 10 00 02 pm" src="https://user-images.githubusercontent.com/42700140/51800162-7fb0e080-227f-11e9-96fc-f2ed80c1c080.png">
<img width="288" alt="screen shot 2019-01-27 at 10 00 11 pm" src="https://user-images.githubusercontent.com/42700140/51800163-7fb0e080-227f-11e9-9baa-531dad9c709a.png">

**Comment by KillerCodeMonkey** [comment]
But you are Not storing Any Formats when using Text?

So the toolbar IS useless?

Am So., 27. Jan. 2019, 12:05 hat Madhavan Sundararaj <
notifications@github.com> geschrieben:

**Comment by Maddy2894** [comment]
Nope, i will be using code formats and some html tags written by user.

**Comment by KillerCodeMonkey** [comment]
Okay :)

Am So., 27. Jan. 2019, 12:07 hat Madhavan Sundararaj <
notifications@github.com> geschrieben:

**Comment by Maddy2894** [comment]
> You are right, but while retrieving, it does not retrieve with a new line. Please see below images for reference. And yea, I could use text area, but toolbar options of WYSIWYG Editor is a requirement.
> 
> <img alt="screen shot 2019-01-27 at 10 00 02 pm" width="545" src="https://user-images.githubusercontent.com/42700140/51800162-7fb0e080-227f-11e9-96fc-f2ed80c1c080.png">
> 
> <img alt="screen shot 2019-01-27 at 10 00 11 pm" width="288" src="https://user-images.githubusercontent.com/42700140/51800163-7fb0e080-227f-11e9-9baa-531dad9c709a.png">

is it possible to retrieve with new line representation?

**Comment by KillerCodeMonkey** [comment]
you could check if there is an existing Blot for that:
https://quilljs.com/guides/how-to-customize-quill/#customizing-blots
