### ISSUE TITLE
Request to update the docs with a reminder that Angular's XSS sanitation is not applied to inputs before passing to quill

### ISSUE THREAD

**Issue by eranation** [KillerCodeMonkey/ngx-quill#232]
This is a quill issue in general, (if you can call it an issue, the authors are not guaranteeing any XSS protection on the client side, all data should be sanitized on the server-side at all times)

Having that said, Angular templates provide some assurance against XSS in the form of client side sanitizing of all inputs https://angular.io/guide/security#xss 

Opening this issue to request update the docs with a warning, since ngx-quill is an angular component, some may have a false expectation that angular will sanitize all inputs to quill. That since ngx-quill is just a wrapper, those XSS sanitation guards given by Angular are not guaranteed, (I assume since quill uses it's own DOM rendering engine independent of Angular for example), 

It is easy to reproduce XSS attacks, e.g. a document content with `<img src="http://www.erorerer.com/a.jpg" onerror="alert(1)" />` will show the alert if used in ngx-quill (or quill directly) but will be sanitized by angular if used elsewhere (e.g. `<div [innerHTML]="'...'"></div>`

A nice to have will be to have ngx-quill sanitize input using Angular's HTML sanitation API before passing it to quill. (perhaps based on a parameter, and make it on by default). 

While users of ngx-quill can do it themselves, (plus have serverside sanitation before persisting) - this can protect a lot of users by being secure by default and not by opt-in.

**Comment by KillerCodeMonkey** [comment]
Feel free to add this Feature and send me a PR ;).

Eran Medan <notifications@github.com> schrieb am Sa., 25. Aug. 2018, 02:59:

**Comment by KillerCodeMonkey** [comment]
implemented in v4.3.0 and added a section to the readme. :) thanks for the important hint ;)

**Comment by KillerCodeMonkey** [comment]
added two examples to my demo repo:
https://killercodemonkey.github.io/ngx-quill-example/

once sanitizing is activated and working and one to show, what could happen

**Comment by f-aubert** [comment]
Would it be possible to partially sanitize the content when OUTPUTTING it, with for example <quill-view-html>? Removing script tags, and events (onclick, ...) attributes would be welcome. Fully bypassing Angular sanitization make injecting javascript easy, and obviously client side sanitization on input is not sufficient as input can manually be edited before being sent to backend.

**Comment by KillerCodeMonkey** [comment]
In general i would say the "input" sanitation is enough, because it strips all the things coming from the backend and could be something "destroying" the frontend or inject scripts. So in most cases you are using this, if you are not trusting the source the html content is coming from.

A client side sanitation will never replace serverside validation/sanitation. As a server you can never trust values coming from a client, because in most cases APIs are used for modern web apps and so an api should be handle those cases as well.

You will not achieve more safety by adding more "sanitation" in special places in the frontend.

Sure if you are using "html" representation if the content (what i not recommend, just use the json/object format) and set the `sanitize` input to true, i could make an angular sanitized string out of it, but this will not absolve you from validating and sanitizing all the thing on server side. :)

**Comment by 99diagha** [comment]
@KillerCodeMonkey Hey, using `sanitize` strips the styles too. Is there a fix for this that I'm not aware of?

**Comment by KillerCodeMonkey** [comment]
Sanatizing should Not Strip Styles. But quilljs does If you are using classbased Styling instead of Inline Styling.

**Comment by 99diagha** [comment]
I'm using this to test it:
`<h2><u>This is </u>a <span style="color: rgb(240, 102, 102);">RICH</span> <strong>text editor</strong><h3><span style="color: rgb(153, 51, 255);">I hope you </span><strong style="color: rgb(153, 51, 255);">like it!</strong></h3>`
The colors are stripped but everything else works fine.

**Comment by 99diagha** [comment]
@KillerCodeMonkey [Here](https://stackblitz.com/edit/angular-markdown-editor-jira-czexb3?file=src/app/app.component.ts) is an example.
