### ISSUE TITLE
Request to update the doc : How to include Quill Stylesheets & Javascript file in the project through angular.json or in index.html

### ISSUE THREAD

**Issue by raydvard** [KillerCodeMonkey/ngx-quill#242]
Please update the doc with the information of including the required stylesheets and js files for quill editor to make it work perfectly.
It will give clear concepts of whole install-to-use process.

Some people messed up with this because some incorrect compilation of required files.

**Comment by KillerCodeMonkey** [comment]
Check Out the readme There is a short section about it ;).

And You add it like for any other lib.
Therefore You have the Scripts section in Your angular.json.

Styling is also added like in other projects. Simply import Quills css and
theme css in Your App.css or add Them via angular.json

raydvard <notifications@github.com> schrieb am Sa., 8. Sep. 2018, 10:54:

**Comment by KillerCodeMonkey** [comment]
And Use issue search. There are similar ones with solutions

Bengt Weiße <bengtler@googlemail.com> schrieb am Sa., 8. Sep. 2018, 11:06:

**Comment by raydvard** [comment]
Yes >
**do not forget to include quill + theme css in your buildprocess, module or index.html!**

How to add live every other lib it can be common, but exactly which files for this quill version should be added and from CDN or should we need to download and then add them? If so, how just show the example.

I am just saying to make that direction more clear to understand easily. 
And you should at least mention those specific file names or sources to direct properly.

**Comment by KillerCodeMonkey** [comment]
Therefore i have also an example repo (no angular-cli), but where You See
how to Use all together.

And in General a Frontend dev Knows how to install packages and Use Them
for the projects tech Stack.

Quill sources are from the quill Repo, ngx-quill is the angular wrapper. In
General the deps Are installed And managed by npm or yarn. So everything
You need is There.

What styling Files You need for quill can be found in the quill
Documentation. If ngx-quill would have custom stylesheet or something You
would Know it, because There would be an readme section about it.

And how to include Them in Your project depends on Your build process. I am
Not an ng-cli expert. So If You are using it, You should Know how to
include external / third Party stylesheets.

How to Use ngx-quill is explained in the Documentation.

So You should be able to Check quilljs Repo/node_Module/Documentation +
angular-cli readme and doc.. And at the end ngx-quill Documentation and
example repo.

And You should Know, that node_modules is the was You go im General. So
quill is installed over npm and You Do Not need to Manual download libs.
The cdn is only an alternativ way of using quill, If You want it.




raydvard <notifications@github.com> schrieb am Sa., 8. Sep. 2018, 11:16:

**Comment by raydvard** [comment]
Thanks for the answer.
Well, to clear out my confusion, 

> What styling Files You need for quill can be found in the quill
Documentation.
Or,
Check Example Demo

This statement can help in the documentation.

**Comment by KillerCodeMonkey** [comment]
added additional hints to the readme
