### ISSUE TITLE
Delta issue

### ISSUE THREAD

**Issue by Kollegos** [KillerCodeMonkey/ngx-quill#247]
I need to add macher to insert plain text only. I find the way in original repo, but have error on this implementation.

`editorInstance.clipboard.addMatcher(Node.TEXT_NODE, node => new Delta(node.plaintext));`

Error:

ERROR Error: Uncaught (in promise): TypeError: quill__WEBPACK_IMPORTED_MODULE_13__.Delta is not a constructor
TypeError: quill__WEBPACK_IMPORTED_MODULE_13__.Delta is not a constructor

Is there any way to fix this or workaround?

**Comment by KillerCodeMonkey** [comment]
öhhh... looks like a typing issue.
do not use the @types/quilljs

and how to you import "Delta"?
Check the quilljs in your node_modules folder, if and where delta is exported.

**Comment by KillerCodeMonkey** [comment]
install latest `@types/quilljs`

and use

```
import { Delta } from 'quill'
```

this seems to work for typing

**Comment by dudewad** [comment]
I'm having this issue now. Is there any other update?

**Comment by dudewad** [comment]
I see -- so my Quill is simply `quill` in node_modules.
You're repeatedly referencing `quilljs` above. Does ngxquill not import its dependencies? Because I don't have that as a project dependency, yet somehow `ngx-quill` works fine.
I also have `quill-delta` which lives alongside the `quill` lib.

**Comment by dudewad** [comment]
FWIW I got it to work. I now have latest `quill-delta`, and am doing:
`import Delta from 'quill-delta';` instead of `import { Delta } from 'quill';`
...and everything seems to work fine. It'd be good to make Quill's whole ecosystem available without having the confusing import system but this is working for now.

**Comment by KillerCodeMonkey** [comment]
There are often issue with the quilljs types (they are not maintained by the quilljs team).
So i think the types where wrong at this time (2018),

And i am not responsible for quill and how they provide their modules.

I only build the angular wrapper for it.
And my wrapper only need quill to be installed as peer dependency, because i got that problems with the typings. (i do not use them anymore for this module)

I see no need that i have to import and re-export everything from another module, especially when i do not node quill-delta ;-).

Seems like quill is using quill-delta so it is automatically installed as dependency, so it is the correct way you are using it.

**Comment by sahilkumarsahoo** [comment]
IN ANGULAR 11

add
```
npm i ngx-quill@15.0.0
npm i --save-dev @types/quill@1.3.10  
```

**I'll solve** import { Delta } **from 'quill' problem**

**Comment by sanjeeb-KL** [comment]
But suppose someone is trying a table with quill v2.0.0-dev.3/4 in that case what dependency, version do we need to add?
