### ISSUE TITLE
onContentChanged - triggers when item is removed from array

### ISSUE THREAD

**Issue by frankspin89** [KillerCodeMonkey/ngx-quill#28]
I have a problem regarding the onContentChanged method. 

In my project I have a array of quill editors. And a user can add a new editor instance to the array and delete one from the array. But when the user delete a editor from the array the onContentChanged method is triggered. 

And that is causing some side effects in my project. Because every time onContentChanged is triggered I save the data to the database. And when I delete a editor from my array,  onContentChanged will add it back ;-(

Is there a way to change the behavior of onContentChanged so it's only watching the content of the current instance of the editor?

**Comment by KillerCodeMonkey** [comment]
this is a special case in your app.

i can not handle anything if you have multiple instances and so on. If you delete an editor in your array it should be destroyed like if an angular component is not persistent in the dom any longer.

Maybe you can share an plunkr example or your code.

If the component is destroyed the onContentChanged of this editor should not be called again, because is content has not changed at all.

It is just like an *ngIf to remove and add it again to dom.

**Comment by frankspin89** [comment]
Hi @KillerCodeMonkey thanks for your response. I agree that this issue is special to my app and not relevant. Closing this issue now.

**Comment by KillerCodeMonkey** [comment]
i would help you... if you need it.. so no repo or code example?
