### ISSUE TITLE
quill 2.0.0-dev.3

### ISSUE THREAD

**Issue by Kollegos** [KillerCodeMonkey/ngx-quill#302]
Is there any chance that the version of ngx-quill for Quill 2.0.0 will be released soon (as dev version)?

**Comment by KillerCodeMonkey** [comment]
My problem with such "dev" releases is, they could change everything in the next dev release, or i need to maintain my dev releases because somebody wants to use a newer quill dev-build.

So in general i want to wait til quill 2.0 is in RC phase.

And i do not know on which version i want to release such things.
If i have some breaking changes in my code i want to follow semantic versioning, so i want to avoid releasing ngx-quill 6.0.0-0 and a week later i release 6.0.0 with quill 1.3.x

**Comment by godenji** [comment]
Understood, but Quill's dev branch has some quite nice-to-have features (e.g. table support). Ngx-Quill targeting Quill 1.x alone is a non-starter wrt to benefiting form 2.x features.

How about a snapshot release? That way there are no binary compatability guarantees, users will know that things can break at any time.

btw, Quill dev branch [commit activity](https://github.com/quilljs/quill/commits/develop) has picked up again, I suspect an RC is imminent.
