### ISSUE TITLE
Keyboard will not close on Ionic 3 App on iOS

### ISSUE THREAD

**Issue by trfletch** [KillerCodeMonkey/ngx-quill#318]
I am trying to get this running on Ionic 3 App on iOS, and it seems to be working okay apart from once I am in the text editor and the virtual keyboard is showing I can’t seem to close the keyboard, usually clicking somewhere else on the page would close the keyboard but this doesn’t seem to work. Also when within the editor and the keyboard showing the header bar with the page title and back button dissappears. Any ideas?

**Comment by KillerCodeMonkey** [comment]
Uhh, never tried it.

Only integrated it in v3 and tested it in the browser:
https://github.com/KillerCodeMonkey/ngx-quill-ionic-v3

Sadly, i do not have any iOS device here. but i can check this in the emulator on my macbook.

The only thing i know is, that you need to do this adjustments in your css:
https://github.com/KillerCodeMonkey/ngx-quill-ionic-v3#how-to-use

**Comment by trfletch** [comment]
I already have the "contenteditable" style in my CSS, just tested it on emulator on Mac and I get the issue on there as well (on iPhone 6s and iPad Pro 12.9-inch). The iPad doesn't hide the header like the iPhone does but I still cannot unfocus the text editor by clicking outside of it unless I click on something like a dropdown list then it seems to go.

**Comment by KillerCodeMonkey** [comment]
Okay could Check this with a plain quilljs Editor (without ngx-quill)?

This seems more like a  quilljs issue.
Or maybe you can Check the Ionic v3 repo for issues with iOS Keyboard and
contenteditable.

Do you included the Ionic Keyboard Plugin?

Maybe you can Close the Keyboard programmatically after a click on the
ioncontent.






Am 17.01.2019 21:43 schrieb "trfletch" <notifications@github.com>:

I already have the "contenteditable" style in my CSS, just tested it on
emulator on Mac and I get the issue on there as well (on iPhone 6s and iPad
Pro 12.9-inch). The iPad doesn't hide the header like the iPhone does but I
still cannot unfocus the text editor by clicking outside of it unless I
click on something like a dropdown list then it seems to go.

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/KillerCodeMonkey/ngx-quill/issues/318#issuecomment-455325044>,
or mute the thread

**Comment by trfletch** [comment]
Just tried the demo link (https://killercodemonkey.github.io/ngx-quill-ionic-v3/) in the Safari browser on iPad simulator and this has the same issue, if you click outside the editor it does not close, whereas if you compare that to the demo of an Ionic input you can see that does close when you click outside of the input (https://ionicframework.com/dist/preview-app/www/?production=true#/input-placeholder).

Yes I don't think this is an issue specific to Quill to be honest, I tried the CKeditor demo on the iPad emulator and this seems to have the same problem.

I will take a look and see if I can find a solution.

**Comment by KillerCodeMonkey** [comment]
Yeah but keep in mind i am not the creator of quilljs, i only maintain this
angular wrapper.

So If you can Reproduce IT with Native quilljs Check the repo for existing
issues.
Or IT is an Ionic Thing. They are setting some iOS specific stuff.

Or at least IT is maybe an iOS Bug :)... Again...




Am Do., 17. Jan. 2019, 21:57 hat trfletch <notifications@github.com>
geschrieben:

**Comment by trfletch** [comment]
Looks like it is an iOS contenteditable issue so I will need to find a solution for it no matter what rich text editor I try and use because I assume they all use contenteditable.

A couple of stack overflow threads that suggest possible fixes just in case someone else comes across this, I will give them a try and see how I get on, thanks for your help:

https://stackoverflow.com/questions/23362575/blur-on-contenteditable-div-on-ipad
https://stackoverflow.com/questions/8949222/closing-keyboard-on-ipad-in-div-contenteditable

**Comment by KillerCodeMonkey** [comment]
your app is a pwa or native app?

Like i suggest for a native app, you could try the programmatically approach with the keyboard plugin.

for a pwa.. i do not know. Maybe i would try to dynamically add and remove the contenteditable attribute or set the editor readonly onBlur and onClick activate it again and setFocus through the quill api.

I close this issue, because it has nothing to do with ngx-quill.

But it would be nice if you post your solution here, if you have one.

Thanks :)
