### ISSUE TITLE
Why will Angular not correctly display the text in HTML format?

### ISSUE THREAD

**Issue by JoelAlbero** [KillerCodeMonkey/ngx-quill#356]
Hello!
Clarification: I do not speak English. To write this text I use Google translate.

I'm having problems viewing content in the editor. I work with the HTML format (I'm using ngModel) and when writing the document it looks perfect.
The problem arises when I want to load the information from the database that does not visuialize as it was previously saved.

For example:
in database I have `<ul><li>1</li><li>2</li><li>3</li></ul>` but when loading the content in the editor it shows me:  `<p> 123 </p>`

Angular CLI = 6.2.9
ngx-quill = 4.6.12

Thank you!

**Comment by KillerCodeMonkey** [comment]
Do you use Chrome? because Chrome has some known issues to strip tags.

In your case i would not store html tags in the database because this is not recommded by quilljs.

Just try it in Firefox or Safari if it is working.

**Comment by JoelAlbero** [comment]
> ¿Usas Chrome? porque Chrome tiene algunos problemas conocidos para quitar etiquetas.
> 
> En su caso, no almacenaría etiquetas html en la base de datos porque quilljs no lo recomienda.
> 
> Solo inténtalo en Firefox o Safari si está funcionando.

Again, I appreciate your response.
The problem happens in both Chrome, Firefox and Opera.

**Comment by KillerCodeMonkey** [comment]
could you create an example repo or stackblitz or something like that?

i have an example repo:
https://killercodemonkey.github.io/ngx-quill-example/

you can clone it here
https://github.com/KillerCodeMonkey/ngx-quill-example

maybe this is a good base to start.

I think this is not a ngx-quill issue. more something with quill, because i am using the quilljs api to insert html.

Could you check if this also happens with native quilljs?
Do other html-strings work?

**Comment by KillerCodeMonkey** [comment]
any updates?

**Comment by KillerCodeMonkey** [comment]
Are you sure, you are using formt html?
I added an example to my demo repo:
https://killercodemonkey.github.io/ngx-quill-example/

The last editor has a htmls list as model. looks good to me.

**Comment by pkojchevski** [comment]
i have the same issue. It s crazy i lost whole day on it and it does not work....
