### ISSUE TITLE
New line added on edit mode

### ISSUE THREAD

**Issue by junimohano** [KillerCodeMonkey/ngx-quill#357]
I found a bug that new line is added between **text** and **ul tags** on edit mode.
I can reproduce it as below of examples

1. Type those text and list using ![image](https://user-images.githubusercontent.com/19492915/54605556-ea7ccd80-4a1f-11e9-8a1e-7e952617ab52.png)
![image](https://user-images.githubusercontent.com/19492915/54605285-45fa8b80-4a1f-11e9-8038-7f8fdacca479.png)

2. and then add **1** next to **hello**
then as you can see, there is ```<p><br></p>``` added
![image](https://user-images.githubusercontent.com/19492915/54605361-7b06de00-4a1f-11e9-919d-5f8abcebefe2.png)

3. after save those html value and reload editor, it will be like that as below
![image](https://user-images.githubusercontent.com/19492915/54605428-9eca2400-4a1f-11e9-9a79-96f30cbf2d35.png)

If you do same thing again (add **2** next to **hello1**), it will add one more new line  ```<p><br></p>```
![image](https://user-images.githubusercontent.com/19492915/54605812-7e4e9980-4a20-11e9-948b-b00714ad39f2.png)

Users try to change text several times without adding new lines, it will have blank lines which users don't want to have.

How do I resolve this or could you fix this issue if this is new issue?

**Comment by KillerCodeMonkey** [comment]
@junimohano could you check this with native quilljs editor?

https://github.com/quilljs/quill/issues/1702

If i am allowed to give you an advice.

Please do not use html strings in general, when storing it to the database.

And in my example repo
https://killercodemonkey.github.io/ngx-quill-example/

i am using divs instead of p-tags. and there seems no issue.
Maybe that could be a workaround for you :)

**Comment by junimohano** [comment]
I already checked your exaple app which has same issue as it doesn't matter **Div** or **P** tag.

```
import { Component } from '@angular/core';

@Component({
  selector: 'app-default',
  templateUrl: './default.component.html'
})
export class DefaultComponent {
  value = '<div>test</div><ul><li>1</li><li>2</li><li>3</li></ul>';
}
```

```
<quill-editor [(ngModel)]="value" [style]="{height: '200px'}"></quill-editor>
{{value}}
```

um, I am not sure how to fix by quilljs/quill#1702
If not use html string, is there any way to save css styling ?

**Comment by KillerCodeMonkey** [comment]
the linked quilljs issue is there because it is maybe related or the same issue.

You can switch from class based stylings to inline stylings, then the object or json representation should contain the styling as "attributes".

**Comment by junimohano** [comment]
I tested by https://quilljs.com/playground/ which is from quilljs

```
<div id="editor-container">
  <div>test</div><ul><li>1</li><li>2</li><li>3</li></ul>
</div>
```

```
var quill = new Quill('#editor-container', {
  modules: {
    toolbar: [
      [{ header: [1, 2, false] }],
      ['bold', 'italic', 'underline'],
      ['image', 'code-block']
    ]
  },
  placeholder: 'Compose an epic...',
  theme: 'snow'  // or 'bubble'
});

quill.on('text-change', function(delta, oldDelta, source) {
  console.log(quill.root.innerHTML);
});

```

Quill js itself seems okay.

**Comment by KillerCodeMonkey** [comment]
when i am using my demo - the last editor:
https://killercodemonkey.github.io/ngx-quill-example/

1. clearing the content
2. writing text "hello"
3. press enter
4. insert a list
5. go up to "hello" and add "1" oder something else

everything looks good in chrome and firefox

<img width="590" alt="Bildschirmfoto 2019-03-19 um 15 10 54" src="https://user-images.githubusercontent.com/2264672/54612427-3a2bbb00-4a59-11e9-9ff4-c89f8fb7175e.png">

**Comment by junimohano** [comment]
When you type from scratch works fine.

Try to give default value ```<div>test</div><ul><li>1</li><li>2</li><li>3</li></ul>``` on code level

and then try to insert **1** next to **test** by typing

It will have one more ```<div><br></div>```

**Comment by junimohano** [comment]
Can you reproduce it?

**Comment by KillerCodeMonkey** [comment]
I am using the clipboard module of quilljs to convert the html-code to the proper quill blots.

`quillEditor.clipboard.convert()`

this returns the multiple new lines.

Calling "clipboard.convert" makes it save to use the values, because they are transformed to valid representation of the content.

Checkout this old issue:
https://github.com/quilljs/quill/issues/672

Seems like convert only checks duplicated trailing new lines.
https://github.com/quilljs/quill/blob/develop/modules/clipboard.js#L80

Maybe there is another issue there that adds newline on wrong positions?

**Comment by junimohano** [comment]
https://junimohano.github.io/reproduce-ngx-quill-bugs/
by the way, here is demo I made.

You can check on the bottom of the page.

Add **1** next to **test**

then you will get additional ```<div><br></div>``` between text and ul


Why not just using innerHTML instead of clipboard?

**Comment by KillerCodeMonkey** [comment]
Because IT IS Not Safe and i do Not want to cause More issues because the
result Looks Not how you want to expect IT ;).

IT IS only a quilljs wrapper and should Not Change quills internal
functionality

So If you are using quill, you would use quills API to manipulate the
content, too.

So you can Open an issue in the quilljs repo for that, because the
Clipboard.convert method adds duplicated New lines.

And AS a workaround Set the Initial value Like you want for example
directly add HTML. But then you have No warranties IT will Work correctly
or will be Future proofed.

The best would be, when you send quilljs a PR with a solution ;)

Jun An <notifications@github.com> schrieb am Di., 19. März 2019, 16:30:

**Comment by junimohano** [comment]
ok, thanks, will try to do it

**Comment by KillerCodeMonkey** [comment]
@junimohano please link the quilljs issue or pr here so we have an association between them :)

**Comment by junimohano** [comment]
As I can see https://quilljs.com/docs/modules/clipboard/, there is a way to customize when we use **convert()**

and I tried to put your component and works fine.

```
Input()
  valueSetter = (quillEditor: any, value: any): any => {
    if (this.format === 'html') {
      if (this.sanitize) {
        value = this.domSanitizer.sanitize(SecurityContext.HTML, value)
      }
      // ******************************************************************
      // here
      quillEditor.clipboard.addMatcher('p', function (node, delta) {
        delta.ops[0].insert = delta.ops[0].insert.replace('\n\n', '\n');
        return delta;
      });
      // ******************************************************************

      return quillEditor.clipboard.convert(value);
    } else if (this.format === 'json') {
      try {
        return JSON.parse(value)
      } catch (e) {
        return [{ insert: value }]
      }
    }

    return value
  }
```

Can you add those function as optional so that I can use it?

**Comment by KillerCodeMonkey** [comment]
I do Not want to, because this would Break the default behaviour when
someone wants multiple New lines. This would replace them.

And the replacement can not bei fixed Set to p-tags because you can Switch
them to divs or Other Blockelements

 I would prefer If the quilljs Team would Check the Convert function if
There IS a Bug.

Btw you could do IT on your own. Remove newlines in Front of list (If this
IS the own Case IT Happens to you) when passing the Data to ngx-quill and
do the Same when storing the values to the Database.

But then keep in mind, If someone wants multiple New lines IT would Strip
them.

Jun An <notifications@github.com> schrieb am Mi., 20. März 2019, 16:35:

**Comment by junimohano** [comment]
Why optional options breaks default behavior?

anyway, never mind ~ thanks

**Comment by KillerCodeMonkey** [comment]
Because at some Point my wrapper quickfix many possible quilljs bugs,
because people want the Editor handle Other things with optional props. And
thats Not how Software development works.

I Like to fix the root Problem. :)

But i think my described workaround should Work?

Jun An <notifications@github.com> schrieb am Mi., 20. März 2019, 19:43:

**Comment by umutkorkut** [comment]
For people having this issue in the future:
Add this line to quill-editor
`[modules]="{ clipboard: {matchVisual: false} }"`

**Comment by KillerCodeMonkey** [comment]
@umutkorkut but keep in mind, that it will be removed in 2.0.0

https://github.com/quilljs/quill/blob/ee827ffb605ba491246f201d497ce0e7d9e193a0/docs/guides/upgrading-to-2-0.md#configuration

**Comment by sergiocabral** [comment]
I have the same problem.
I solve with this trick:
![image](https://user-images.githubusercontent.com/665373/78034016-8cc2d700-733d-11ea-81af-f64afbe506d1.png)

The problm is when de component internally convert html to text, any paragraph is converted to text with new line at end. So, the component convert internally text to html again, then any text is put into paragraph <p>, but when found a new line it converted to other paragraph <p><br></p> generaing new lines foreever.

**Comment by sirajalam049** [comment]
@sergiocabral . That worked like a charm. Thank you.

**Comment by msteel9999** [comment]
Just to make it easier for the next person I called this on loading the value from the database and this is the code:

`.replace('/<p><br><\/p>/g', '<br>')
.replace(/<p>/g, '')
.replace(/<\/p>/g, '<br>')
`

**Comment by Zinoberous** [comment]
I have the same problem with primereact, the value is misinterpreted. Do someone know a solution?:

https://primereact.org/editor/
https://stackblitz.com/edit/dinceg?file=src%2FApp.tsx

```
import React, { useState } from 'react';
import { Editor, EditorTextChangeEvent } from 'primereact/editor';

export default function BasicDemo() {
  const [text, setText] = useState<string>('<p>Test</p><ul><li>a</li><li>b</li></ul>');

  return (
    <div className="card">
      <Editor
        value={text}
        onTextChange={(e: EditorTextChangeEvent) => {
          console.log(e);
          setText(e.htmlValue);
        }}
        style={{ height: '320px' }}
      />
    </div>
  );
}
```

**Comment by KillerCodeMonkey** [comment]
But this is ngx quill... for angular...

Am 6. April 2024 12:49:11 MESZ schrieb Zinoberous ***@***.***>:

**Comment by Zinoberous** [comment]
Primereact-Editor is based on Quill and I saw the exact same problem here so I thougt I try to ask here for maybe some aranged developers. ^^'

**Comment by stability-newfound43** [comment]
Take a peek at this reply



https://angulardev.space/questions/the-ngx-quill-module-fails-to-properly-sanitize-html-strings
