### ISSUE TITLE
Unable to store the html content and display again for edit purpose?

### ISSUE THREAD

**Issue by PrasadChinthala** [KillerCodeMonkey/ngx-quill#386]
I am working on a requirement where I have to add & edit the content using quill-editor, the data is getting stored into database that is fine but after saving again I have to retrieve it for edit purpose. While storing the content p tags are not adding to the content. I dont know how to fix it, I am new to quill editor & angular as well. I have searched for solution but I dint find any solution working So came here.

quill-editor HTML:

```html
<quill-editor [style.display]="'block'" (onEditorCreated)="onEditorCreated($event)" [style.height]="'400px'" formControlName="body" #description>
        </quill-editor>
```

My component.ts file:

```ts
import { QuillEditorComponent } from 'ngx-quill';
export class EditMailTemplateComponent implements OnInit {
@ViewChild('description') description: QuillEditorComponent; 
public editor; editForm() {
this.mailTemplateForm = this.fb.group({
      id: 0,
      name: [''],
      body: [''],
});
}
getFormData() {
  this.editForm();
  this.mailTemplateForm.patchValue(this.data.form_data);
}
onEditorCreated(event) {
    this.editor = event;
  }
onSubmit() {
   this.mailTemplateForm.controls.body.setValue(this.editor.getText());
}
appendTagTo(textTOInsert: string) {
    console.log('called - ', textTOInsert);
    textTOInsert = '{{'+textTOInsert+'}}';
    const selection = this.editor.getSelection(true);
    this.editor.insertText(selection.index, textTOInsert);
 }
}
```

Please where I am doing the mistake is it whiie storing the content into database or while retrieving the data? Thanks for your help.

**Comment by KillerCodeMonkey** [comment]
first of all:

If you are using ngModel or formControls, than this should be the single source of your content.
So instead of `this.editor.insertText(selection.index, textTOInsert);` you can directly change your formControls and it will be update the editor content.

You are using a formControl and setting values to this control with the quill api, but ngx-quill + angular is doing this for you.

So the flow would be:

1. init a formControl, set the data from your database to the control
2. connect your ngx-quill-editor component in the template with this formControl
3. Change the content in the editor (not programmatically)
4. ngx-quill will automatically update your formControl to the changed values (check the demo-repo there you can see reactive forms ;))
5. If you save the value to the database, just use your formControl value

And now code how easy it should be

```ts
import { QuillEditorComponent } from 'ngx-quill';
export class EditMailTemplateComponent implements OnInit {
  mailTemplateForm: FormGroup

  ngOnInit() {
    // LoadDataFromDatabase here = data
    // disable or hide the form until the init data is loaded :)
    this.mailTemplateForm = this.fb.group({
      id: [data.id || 0],
      name: [data.name || ''],
      body: [data.body || ''],
    });
  }

  onSubmit() {
    // All user inputs are automatically store on this.mailTemplateForm.get('body').value
    // just send it to you backend
  }
}
```

ngx-quill is usigng `html` format as default format. But you are setting the text-value of the editor to the formControl, so you only get the plain text ;). Check the readme and the format config.

And please checkout the live-demo and the example repo.
