### ISSUE TITLE
Using Grammarly Breaks Quill

### ISSUE THREAD

**Issue by blundercode** [KillerCodeMonkey/ngx-quill#40]
1. [What is Grammarly ](https://www.grammarly.com/faq)
2. [Download Chrome Extension](https://app.grammarly.com/apps)
3. Visit [Demo Page](https://killercodemonkey.github.io/ngx-quill-example/)
4. Attempt to use Quill while Grammarly is enabled.

When Grammarly is enabled on a page that uses the ngx-quill Editor the editor is rendered basically useless, making selecting text impossible and inserting text into the middle of a sentence impossible. The editor I'm using to write this isn't having problems so I know it's possible to correct this issue.

Grammarly is used by a huge amount of people just wanted to let you know about this. So more devs can adopt Quill without worry of users not being able to use the editor.

**Comment by KillerCodeMonkey** [comment]
Did you checked if this works with pure QuillJS. Or do you have any idea how to disable grammarly or such plugins in general for Quill?

**Comment by KillerCodeMonkey** [comment]
@blundercode i checked it out --> this issues has something to do with latest quill versions I think. When I try it with QuillJS 1.0.0-beta.3 or some other beta version it seems some how to work with Grammarly.

Since the RC releases, it does not work anymore.

This occurs also in the ng-quill repo. There you can easily play around with the quill versions in the `demo.html`.

**Comment by blundercode** [comment]
So we just have to wait to wait till its fixed in Quill-Js? I can look into a fix and create a PR for it when I get a moment if you think it's worth fixing now?

**Comment by KillerCodeMonkey** [comment]
feel free 👍

**Comment by KillerCodeMonkey** [comment]
Check out Jason Chen's answer to this topic:
https://github.com/quilljs/quill/issues/574

So, i think i can close this here
