### ISSUE TITLE
Regression between 6.3.0 and 6.3.1

### ISSUE THREAD

**Issue by anisabboud** [KillerCodeMonkey/ngx-quill#412]
Version `6.3.0` works for me, but after upgrading ngx-quill to `6.3.1` (which was released an hour ago) I am getting console errors (rolling back to 6.3.0 works):

![image](https://user-images.githubusercontent.com/5672108/60522356-7970d580-9cf1-11e9-8a87-71119850d1bc.png)

**Comment by KillerCodeMonkey** [comment]
how did you use ngx-quill in your main component?

**Comment by KillerCodeMonkey** [comment]
i fixed something for lazy loading... this leads to a breaking change, because the previous usage of the QuillModule was wrong and wrong documented. sorry.

I updated the readme an released 7.0.0

Where you have to import the QuillModule this way.

`QuillModule.forRoot()` in your main module.

and in all LazyLoaded onces only with `QuillModule`

**Comment by anisabboud** [comment]
Thank you! version 7.0.0 works for me with `QuillModule.forRoot()`.

**Comment by KillerCodeMonkey** [comment]
nice thanks for letting me know.

Do you use lazy loaded modules? Could you check if this is also working?

**Comment by anisabboud** [comment]
I don't yet use lazy loading.
