### ISSUE TITLE
add a counter for content length without tag

### ISSUE THREAD

**Issue by Tzanou123** [KillerCodeMonkey/ngx-quill#679]
Hi dude,
First thanks for your amazing module, so nice to use !
Im looking for a way to count length of the editor content without the html tag etc ....
i see you had a min-length and max-length who seems to count the length but no way to get the number for tell the user how many letter are added ! 
Any idea for me please !

**Comment by KillerCodeMonkey** [comment]
hey, checkout my demo repo there should be a custom module for letter counting :)

here is a custom Quill Module
https://github.com/KillerCodeMonkey/ngx-quill-example/blob/master/src/app/counter.ts

i use it in this example:
https://github.com/KillerCodeMonkey/ngx-quill-example/tree/8fbcde23bbce90b291a7c8881c72b556e9efd416/src/app/custom-toolbar

In general the Ouput onEditorContentChanged gives you the current content as html, text and object. In general you can use the text.length (-1 because quill adds a \n at the end of each content)

**Comment by Tzanou123** [comment]
thanks a lot dude

**Comment by KillerCodeMonkey** [comment]
you're welcome

Feel free tom close the issue, if you got it working ✌️

**Comment by Tzanou123** [comment]
i am in break i will test it in an hour and will close it for sure
