### ISSUE TITLE
Build ssr, no error but quill-view not rendered Angular 8

### ISSUE THREAD

**Issue by kevinrichard31** [KillerCodeMonkey/ngx-quill#796]
Hi, im using ngx quill on angular universal. I have json format and I use quill-view tag
But while I run my npm run serve:ssr. In the source code, **the json is not rendered.**

The npm run build:ssr command doesn't give me any error !

im using:
```
    "ngx-quill": "^8.0.0",
    "quill": "^1.3.7",
```

**Comment by KillerCodeMonkey** [comment]
do you have any example repo?

**Comment by kevinrichard31** [comment]
Builded SSR project:
https://i.imgur.com/NBXzn8O.gif

As you can see, the hello world works but in the code source he is not interpreted by angular universal.
But while I use the class ql-container 

```
    <div class="ql-container ql-snow" style="border-width: 0;">
      <div class="ql-editor" [innerHTML]="detail">
      </div>
    </div>
```

It works. But to show the content, I have to Parse my json and convert delta to html...
I would like use the quillview, it's more simple. if you have any solutions.

**Comment by KillerCodeMonkey** [comment]
i never used angular universal, so i do know what you mean with "hello world works but in the code source he is not interpreted by angular universal".

In general quill can not be rendered on server side. everything is done on client side, because quilljs depends on "document" and "window" which only exists in browser envs.

If you want to precompile your quill deltas on serverside try something like this:
https://www.npmjs.com/package/node-quill-converter

**Comment by KillerCodeMonkey** [comment]
Check this line:
https://github.com/KillerCodeMonkey/ngx-quill/blob/master/src/quill-view.component.ts#L84

Quill is only initialised by when you are not on server side. If the component gets instantiated on clientside a quilljs instance is created and renders a quilleditor in readonly mode without a toolbar

**Comment by kevinrichard31** [comment]
I mean: If you build your project without universal. Javascript will not convert to html your data binded
If you use SSR. data api Ajax Call and data binding will be retrieved into html in source. ( for SEO ) 

**That's what happen here >**
ql-container class use angular and angular universal. so the content is interpretated by the SSR
But quill-view tag is not. maybe because it's not declared before in SSR angular universal or something else

**Comment by KillerCodeMonkey** [comment]
yep but as i descriped i and you can not achieve this with quilljs, because it depends on the browser ;-) and i render nothing when prerendered on serverside, but if you are on client side.

I do not know exactly how important it is for seo purposes, because google bots can interpret javascript and hopefully - angular is a google product - can interpret angular apps.
(https://react-etc.net/entry/does-googlebot-render-angular-2-without-angular-universal)

If you want to get the content of you quilldata rendered to the html when rendered on server side you can not use this component.
