### ISSUE TITLE
Render formula without an editor

### ISSUE THREAD

**Issue by JairDiaz23** [KillerCodeMonkey/ngx-quill#80]
Hi, I was wondering if it's possible to render any saved data with its format without an instance of quill. I've just accomplished this (with innerHTML) but I have some problems when trying to render the formulas, it looks like the formula is not passing through katex in order to being render in a correct form.

Do you have any idea if it's possible to do this, or any workaround would be very appreciated. Thanks a lot.

**Comment by KillerCodeMonkey** [comment]
never tried it myself.

Did you added katex css and js on the pages, where you render it without quilljs?

**Comment by JairDiaz23** [comment]
Yes, I added, I think the problem is that it adds others characters that are not recognized outside the quill's editor. Like in the image I attach It adds interrogation marks, but once I render the same code and content in the editor it renders ok.

![prueba 2](https://user-images.githubusercontent.com/22720824/32919574-0065b21a-caec-11e7-97eb-944d013cee7c.PNG)
![prueba 1](https://user-images.githubusercontent.com/22720824/32919575-00795fe0-caec-11e7-847d-e70b4d8c5af1.PNG)

**Comment by KillerCodeMonkey** [comment]
strange Oo 

so another approach would be to not grab the html content of the editor. Instead use the parchment representation.

The last thing i know about those issues: Use a quill editor without toolbar and in readonly mode to display things on your site or piece of code ;).

Checkout this:
https://github.com/quilljs/quill/issues/993

So sadly i will close this issue, because it is a known quilljs related issue. But maybe some of my hints are helping you out. If not --> ask in the quill repo
