### ISSUE TITLE
Angular2 Reactive Forms (blur) not firing on quill-editor element

### ISSUE THREAD

**Issue by abembecker** [KillerCodeMonkey/ngx-quill#81]
Expected Behavior:
(blur)="" event handler called when user clicks away from quill-editor element

Observed Behavior:
function in (blur) attribute value never called. See doesNotGetCalled() in plunk:
https://plnkr.co/edit/ufDUXZ9IgAOyE7poYaeD?p=preview

I tried adding contenteditable=true and tabindex="-1", but still does not work..

**Comment by KillerCodeMonkey** [comment]
yeah. because it is a custom component. blur is only available on input types or textareas ;). But there is a custom event called "onSelectionChanged" it should be called if you change the cursor position/leaving the editor.

See: https://killercodemonkey.github.io/ngx-quill-example/
"Editor without toolbar + required and ngModule" example

open JS-Console --> if you click in the editor or outside of the editor, you will get informed.

If you click outside of the editor the event object looks like this:
```
{editor: Quill, range: null, oldRange: Range, source: "user"}
```

**Comment by abembecker** [comment]
Thank you so much for the quick response - works beautifully!
