### ISSUE TITLE
Syntax highlighter

### ISSUE THREAD

**Issue by RolfVeinoeSorensen** [KillerCodeMonkey/ngx-quill#9]
Hi
This might be the wrong place for my question but here goes...

I have added angular2-highlight-js and it works very well inside quill.

But when I want to display syntax highlighted code outside quill I am not able to get it working.
On the element i set:
`highlight-js-content=".highlight"`
This is according to the docs in highlight. But quill saves it:
`<pre class="ql-syntax" spellcheck="false">`

Any idea on how I can make this work?

In advance thank you.

**Comment by RolfVeinoeSorensen** [comment]
I found a simple solution but I dont know if there is a better one?
Simply used the quill module to load the content and set it to readonly.
Works like a charm. And this way I dont have to implement custom code like:
https://github.com/quilljs/quill/blob/develop/modules/syntax.js

**Comment by KillerCodeMonkey** [comment]
ehhm maybe you can show me a little bit more code?

**Comment by KillerCodeMonkey** [comment]
I think you need to initialize highlightjs for the element you want to style.

**Comment by KillerCodeMonkey** [comment]
any updates?

**Comment by RolfVeinoeSorensen** [comment]
Well I found that are two ways to make it load either just let init through quill or copy and implement the functions from the js i posted earlier. Then in code init the highlight on contents with ql-syntax class name.

You may close the issue.

**Comment by KillerCodeMonkey** [comment]
nice. thank you for the update!

**Comment by sharath1608** [comment]
I just stumbled across this and wanted to add some clarity. Specifically, to enable syntax highlighting use the following..
`<quill-editor
              [modules]="{syntax:true,toolbar: [['code-block']]}"
 </quill-editor>`

**Comment by Awatatah** [comment]
I was able to achieve this by adding to `highlight.js` dependencies to the `index.html` head:
```
<link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/highlight.js/9.13.1/styles/monokai-sublime.min.css">
<script src="//cdnjs.cloudflare.com/ajax/libs/highlight.js/9.13.1/highlight.min.js"></script>
<script>
	hljs.configure({
	    languages: ['javascript', 'ruby', 'bash']
	});
</script>
```
then editing `ngx-quill/src/quill-editor.interfaces.d.ts` with:

```
...
export interface QuillModules {
    toolbar: QuillToolbarConfig;
    syntax: boolean;
}
...
```

Then in `app.module.ts`
```
...
const toolbarOptions = [
  { size: [ 'small', false, 'large', 'huge' ]},
  {},
  'bold',
  'italic',
  'underline',
  'strike',
  'link',
  'image',
  {},
  { 'color': [] },
  { 'background': [] },
  {},
  { 'indent': '-1'},
  { 'indent': '+1' },
  { 'list': 'ordered'},
  { 'list': 'bullet' },
  { 'align': [] },
  {},
  'code-block', //<---
  'clean'
];

...

@NgModule({
  imports: [
    ...,

    QuillModule.forRoot({
      modules:{
        syntax: true,
        toolbar: [toolbarOptions]
      }
    }
    ),
  ],
  ...
})
export class AppModule { }
```

This is working great for me but of course, you will need to do this every time a fresh `npm install` is ran. I am going to ask for change request.

**Comment by jdgamble555** [comment]
In order to get highlighting to work when viewing, you can't use "**quill-view-html**," and you can't simply invoke the regular javascript to search the dom, since we are using angular here. You could install **ngx-highlightjs** (one more include why not), or you can display a readOnly quill-editor from above like so as a work around:

```
<quill-editor [modules]="{ syntax: true, toolbar: false }" [styles]="{ border: '0px' }" [readOnly]="true [ngModel]="post.content"></quill-editor>
```

Perhaps @KillerCodeMonkey would be so kind to add this feature to **quilll-view-html**... :)

**Comment by KillerCodeMonkey** [comment]
you know there is another component, called "quill-view" which does the things you do for you :D. 

I do not want to inject or load highlightjs as part of my lib. In general when using html format you only need to load and highlightjs css (as described in the highlighjs repo or when used in the editor) and quill-view-html should render code blocks correctly, because quilljs is adding the hljs css classes to the html-tags:

<img width="725" alt="Bildschirmfoto 2020-04-19 um 08 46 13" src="https://user-images.githubusercontent.com/2264672/79681393-3d741600-821a-11ea-8346-c88be5c39d21.png">

**Comment by jdgamble555** [comment]
Wow.  I did not need all that.

This is even overkill:
```
<quill-view [modules]="{ syntax: true } "[content]="htmlContent"></quill-view>
```
When this works fine:
```
<quill-view-html [content]="htmlContent"></quill-view-html>
```
Just needed to import a SPECIFIC css file:
```
https://cdnjs.com/libraries/highlight.js/
```
Thanks!

**Comment by Sangram9693** [comment]
nice article for [code highlighting](https://blog.almightytricks.com/2020/10/27/code-highlighting-ngx-quill/)
