### ISSUE TITLE
fusebox breaking on weird import line

### ISSUE THREAD

**Issue by jpike88** [KillerCodeMonkey/ngx-quill#902]
https://github.com/KillerCodeMonkey/ngx-quill/blob/572a826d10f289d9a81492e759ff85a823feceef/projects/ngx-quill/src/lib/quill.service.ts#L20

This line is causing my file to transpile incorrectly. I'd usually keep this to the bundler, but that import line looks to me like a break waiting to happen across other bundlers out there.

Looks like the ```.default``` is the issue here.

**Comment by KillerCodeMonkey** [comment]
do you have quill typings v1.3.10 installed?

this is an async import to provide ssr rendering out of the box.
And do not know if fusebox is supporting this feature.
But general umd, webpack projects should work with it.

**Comment by KillerCodeMonkey** [comment]
i have no experiences with fusebox, so i only googled a littel bit and found, then somebody are added 

`experimentalFeatures: true,`

to their config to get dynamic imports working. In general this is working this way, because my demo repo (bundled with webpack and angular-cli) works in production.

But in general i do not know how fusebox is working. And maybe you can share the real error message and how you integrate ngx-quill in your project?

**Comment by nchanged** [comment]
It might be related to the fact that the library doesn't have a `default` export. And FuseBox doesn't polyfill dynamic imports. I am not sure how to address that issue.
Do we need to apply a default polyfill on that?

**Comment by KillerCodeMonkey** [comment]
Do not know that either :), because i just following the angular way building projects. So in general everything should working with angular cli, webpack or systemjs.

So do not support here that much 🤷‍♂️

**Comment by jpike88** [comment]
This is the only library of all the many ones I'm using that has this specific problem, which is a shame. I'm submitting a PR for compatibility, you don't want a non-standard way of importing things to be a problem. Stay tuned

**Comment by jpike88** [comment]
https://github.com/KillerCodeMonkey/ngx-quill/pull/906

**Comment by KillerCodeMonkey** [comment]
merged and released in 10.0.2
