### ISSUE TITLE
this being redefined to the quill toolbar instance when adding handler

### ISSUE THREAD

**Issue by nikmartin** [KillerCodeMonkey/ngx-quill#94]
```

<quill-editor #editor [style]="{height: '500px'}" [(ngModel)]="editorContents" [readOnly]="false" (onEditorCreated)="editorInit($event)"
        [modules]="moduleConfig"></quill-editor>

editorInit(quill) {
    quill.getModule('toolbar').addHandler('image', this.image2);
    quill.focus();
  }

  image2() {
    const filer = this.fileInput.nativeElement; <<<<<<<<
    filer.setAttribute('accept', 'image/png, image/gif, image/jpeg, image/bmp, image/x-icon');
    filer.classList.add('ql-image');
    filer.click();
    filer.addEventListener('change', () => {
      if (filer.files != null && filer.files[0] != null) {
        this.ds.addInlinePic(filer.files[0], this.classid).then(url => {
          const range = this.editor.getSelection();
          this.editor.insertEmbed(range.index, 'image', url);
        });
      }
    });
  }
```

Inside image2. I get:

core.js:1427 ERROR TypeError: Cannot read property 'nativeElement' of undefined
    at Toolbar.EditorComponent.image2 (editor.component.ts:147)
    at HTMLButtonElement.eval (quill.js:9252)
    at ZoneDelegate.invokeTask (zone.js:421)
    at Object.onInvokeTask (core.js:4744)
    at ZoneDelegate.invokeTask (zone.js:420)
    at Zone.runTask (zone.js:188)
    at ZoneTask.invokeTask [as invoke] (zone.js:495)
    at invokeTask (zone.js:1536)
    at HTMLButtonElement.globalZoneAwareCallback (zone.js:1562)

and when I inspect 'this', it's:
```
Toolbar {quill: Quill, options: {…}, container: div.ql-toolbar.ql-snow, controls: Array(15), handlers: {…}}container: div.ql-toolbar.ql-snowcontrols: (15) [Array(2), Array(2), Array(2), Array(2), Array(2), Array(2), Array(2), Array(2), Array(2), Array(2), Array(2), Array(2), Array(2), Array(2), Array(2)]handlers: {clean: ƒ, direction: ƒ, indent: ƒ, link: ƒ, list: ƒ, …}options: {container: Array(7), handlers: {…}}quill: Quill {options: {…}, container: div.ql-container.ql-snow, root: div.ql-editor, scrollingContainer: div.ql-editor, emitter: Emitter, …}__proto__: Module
```
Because this is angular, I take a peek at _this, and it's also set to the toolbar.

**Comment by KillerCodeMonkey** [comment]
Yeah because "this" in your image2 handler is not the "this" you think it
is.

Add a console log, and you will See it

quill.getModule('toolbar').addHandler

Passes another "this" to the Funktion callback than your component context.

So this.fileinput seems to be undefined.


It has nothing to do with this repo ;)



Am 08.01.2018 21:23 schrieb "Nik Martin" <notifications@github.com>:


<quill-editor #editor [style]="{height: '500px'}"
[(ngModel)]="editorContents" [readOnly]="false"
(onEditorCreated)="editorInit($event)"
        [modules]="moduleConfig"></quill-editor>

editorInit(quill) {
    quill.getModule('toolbar').addHandler('image', this.image2);
    quill.focus();
  }

  image2() {
    const filer = this.fileInput.nativeElement; <<<<<<<<
    filer.setAttribute('accept', 'image/png, image/gif, image/jpeg,
image/bmp, image/x-icon');
    filer.classList.add('ql-image');
    filer.click();
    filer.addEventListener('change', () => {
      if (filer.files != null && filer.files[0] != null) {
        this.ds.addInlinePic(filer.files[0], this.classid).then(url => {
          const range = this.editor.getSelection();
          this.editor.insertEmbed(range.index, 'image', url);
        });
      }
    });
  }

Inside image2. I get:

core.js:1427 ERROR TypeError: Cannot read property 'nativeElement' of
undefined
at Toolbar.EditorComponent.image2 (editor.component.ts:147)
at HTMLButtonElement.eval (quill.js:9252)
at ZoneDelegate.invokeTask (zone.js:421)
at Object.onInvokeTask (core.js:4744)
at ZoneDelegate.invokeTask (zone.js:420)
at Zone.runTask (zone.js:188)
at ZoneTask.invokeTask [as invoke] (zone.js:495)
at invokeTask (zone.js:1536)
at HTMLButtonElement.globalZoneAwareCallback (zone.js:1562)

and when I inspect 'this', it's:

Toolbar {quill: Quill, options: {…}, container:
div.ql-toolbar.ql-snow, controls: Array(15), handlers: {…}}container:
div.ql-toolbar.ql-snowcontrols: (15) [Array(2), Array(2), Array(2),
Array(2), Array(2), Array(2), Array(2), Array(2), Array(2), Array(2),
Array(2), Array(2), Array(2), Array(2), Array(2)]handlers: {clean: ƒ,
direction: ƒ, indent: ƒ, link: ƒ, list: ƒ, …}options: {container:
Array(7), handlers: {…}}quill: Quill {options: {…}, container:
div.ql-container.ql-snow, root: div.ql-editor, scrollingContainer:
div.ql-editor, emitter: Emitter, …}__proto__: Module

Because this is angular, I take a peek at _this, and it's also set to the
toolbar.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/KillerCodeMonkey/ngx-quill/issues/94>, or mute the
thread

**Comment by nikmartin** [comment]
Oh I think I see now, when I add that Handler to the add Handler function it is actually being called from the toolbar component so this is actually in context of the toolbar, not my module. So that means I'll have to add that file input control to the editor at runtime when the when the Callback is being run.

**Comment by KillerCodeMonkey** [comment]
Or you bind the context.

Checkout the "bind" function for a JavaScript Funktion ;).

Please, close the issue if you solved your Problem.

Thanks

Am 08.01.2018 21:48 schrieb "Nik Martin" <notifications@github.com>:

**Comment by nikmartin** [comment]
> Checkout the "bind" function for a JavaScript Funktion ;).

DOH! I totally forgot about doing  ` quill.getModule('toolbar').addHandler('image', this.image2.bind(this));`
