### ISSUE TITLE
QuillEditorComponent's isPlatformServer conditional does not prevent quill's many "document is not defined" SSR runtime errors

### ISSUE THREAD

**Issue by omboapp** [KillerCodeMonkey/ngx-quill#966]
**"document is not defined"** errors occur within internal `quill` module imports, when serving a compiled server-side rendering (SSR) build via `@nguniversal/express-engine@10.0.1` and `ngx-quill@12.0.1`. Perhaps newer versions of `quill` (vs `ngx-quill`'s `quill@1.3.7`) will remedy this?

Due to `webpack` creating many nested anonymous closures, I cannot successfully create a dummy `document` object within any global context reachable by internal `quill` modules . To no avail, I have tried mocking these objects in numerous permutations within `universal.zip` equivalent `server.ts` and `main.server.ts` files.

**Comment by omboapp** [comment]
@KillerCodeMonkey, what do you think about this?

**Comment by KillerCodeMonkey** [comment]
I die Not checked your issue, yet. Because i am on my weekend and have
Other things on my schedule. So i will check it tomorrow.

Die you tried to Upgrade my angular Universal Demo?

It is working with angular 9 and quill.

I do Not know any breaking Change, why IT should Not Work The Same way with
angular 10.

Ombo <notifications@github.com> schrieb am So., 12. Juli 2020, 19:39:

**Comment by KillerCodeMonkey** [comment]
@omboapp i have updated my angular universal demo repo an it works like charme.
