### ISSUE TITLE
Editor does not show some HTML elements when the Editor is inside a Tab

### ISSUE THREAD

**Issue by maiazera** [KillerCodeMonkey/ngx-quill#969]
It seems like that the editor is removing some HTML elements like uls, ols and headings when the editor is inside a tab.

<img width="793" alt="Bildschirmfoto 2020-07-13 um 16 05 57" src="https://user-images.githubusercontent.com/13309842/87314761-fb5e2600-c523-11ea-81e8-4413d5d1d84f.png">

```
<mat-tab-group>
  <mat-tab label="First"> Content 1 </mat-tab>
  <mat-tab label="Second"> <quill-editor [ngModel]="'<ul><li>testing</li></ul>'">
  </quill-editor> </mat-tab>
  <mat-tab label="Third"> Content 3 </mat-tab>
</mat-tab-group>
```

**Comment by KillerCodeMonkey** [comment]
check:

https://github.com/KillerCodeMonkey/ngx-quill/issues/198
https://github.com/KillerCodeMonkey/ngx-quill/issues/404

i am not an angular material expert, but material is very complex and does strange things.

So my demo repo contains an mat-quill example, maybe this is working for you.

I will not add any material ui specific thing to this repo, because it is working with angular, and that's it.

**Comment by Rajeshsekaran4488** [comment]
@KillerCodeMonkey ,  
Facing this similar issue, except for Tab am using custom built Stepper.   
Here the HTML string renders at first load (for the active step).
when  in move to next stepper <p> is not rendered as in the HTML.  

Can you help...

**Comment by hoanmq** [comment]
Why you wrap all html to P tag ??? WHYYYYY

**Comment by KillerCodeMonkey** [comment]
Me? Thats the quilljs standard. So ask there. But check out my example
repo, you can change the tag to divs ;-).



hoanmq ***@***.***> schrieb am So., 29. Aug. 2021, 01:59:
