### ISSUE TITLE
On blur and touched not behaving the same as Angular input

### ISSUE THREAD

**Issue by emeryowa** [KillerCodeMonkey/ngx-quill#989]
It looks like the blur event behaves differently in Angular inputs vs Angular Quill editor. This impacts the value of `touched` on form controls

See https://stackblitz.com/edit/ngx-quill-example-ljm59v?file=src%2Fapp%2Fapp.component.ts

Example:
* When I type into the textarea, the blur event is triggered when I click the button or click anywhere on the page outside of Quill editor. The `touched` state is set to true as expected
* When I type into Quill editor, the blur event is triggered when I click anywhere on the page outside of Quill editor, except on the button. If I click the button, the blur event is not triggered and the `touched` value remains false. I would have expected for this to behave like any other input in Angular.

Is there any reason for it to behave this way?
If no, can this be fixed?
If yes, how can I retrieve the correct `touched` state when the user clicks the button?

**Comment by KillerCodeMonkey** [comment]
This is a problem with quilljs not ngx-quill.

The quill editor gets "blurred" when there is no currect selection in the editor.
So quill does not distinguish between clicking a button somewhere else and clicking a button in the toolbar.
Because clicking a button in the toolbar does not Blur the quill instance it just change the active formatting.

See here: https://github.com/quilljs/quill/issues/2186

there are many issues about it.
